## Using `soccerdata` to scrape FBref data

In [1]:
import soccerdata as sd
print(sd.FBref.available_leagues())

[05/30/26 11:25:51] INFO     No custom team name replacements found. You can configure these in       ]8;id=15495973;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_config.py\_config.py]8;;\:]8;id=15495974;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_config.py#92\92]8;;\
                             /Users/fungs4/soccerdata/config/teamname_replacements.json.

                    INFO     Custom league dict loaded from                                          ]8;id=15495980;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_config.py\_config.py]8;;\:]8;id=15495981;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_config.py#188\188]8;;\
                             /Users/fungs4/soccerdata/config/league_dict.json.

['ARG-Primera Division', 'AUT-Bundesliga', 'BEL-First Division A', 'BRA-Serie A', 'Big 5 European Leagues Combined', 'CZE-First League', 'ENG-Premier League', 'ENG2-EFL Championship', 'ESP-La Liga', 'FRA-Ligue 1', 'GER-Bundesliga', 'GRE-Super League', 'INT-European Championship', "INT-Women's World Cup", 'INT-World Cup', 'ITA-Serie A', 'JPN-J1 League', 'KOR-K League 1', 'MEX-Liga MX', 'NED-Eredivisie', 'POR-Primeira Liga', 'SAU-Saudi Pro League', 'SCO-Premiership', 'SUI-Super League', 'TUR-Super Lig', 'USA-MLS']

In [2]:
import soccerdata as sd
import pandas as pd

all_leagues = [
    "ENG-Premier League", "ESP-La Liga", "FRA-Ligue 1", "GER-Bundesliga", "ITA-Serie A",
    "NED-Eredivisie", "POR-Primeira Liga", "SAU-Saudi Pro League", "TUR-Super Lig",
    "BEL-First Division A", "SCO-Premiership", "GRE-Super League", "CZE-First League",
    "AUT-Bundesliga", "SUI-Super League", "BRA-Serie A", "ARG-Primera Division",
    "USA-MLS", "MEX-Liga MX", "KOR-K League 1", "JPN-J1 League", "ENG2-EFL Championship",
]

all_stats = []
for league in all_leagues:
    try:
        fbref = sd.FBref(leagues=[league], seasons=2025)
        s = fbref.read_player_season_stats(stat_type="standard")
        all_stats.append(s)
        print(f"{league}: {s.shape[0]} players")
    except Exception as e:
        print(f"{league}: ERROR — {e}")

stats = pd.concat(all_stats)
print(f"\nTotal players: {stats.shape[0]}")

# Coverage check
players = pd.read_csv("../data/processed/player_fixtures.csv")
wc_players = players[["player", "team", "position"]].drop_duplicates()

stats_names = set(stats.index.get_level_values("player").str.lower().str.strip())
wc_players["name_lower"] = wc_players["player"].str.lower().str.strip()

matched = wc_players[wc_players["name_lower"].isin(stats_names)]
unmatched = wc_players[~wc_players["name_lower"].isin(stats_names)]

print(f"Matched: {len(matched)} ({len(matched)/len(wc_players)*100:.1f}%)")
print(f"Unmatched: {len(unmatched)} ({len(unmatched)/len(wc_players)*100:.1f}%)")

match_rate_by_team = (
    wc_players.groupby("team")
    .apply(lambda g: g["name_lower"].isin(stats_names).mean())
    .sort_values()
)
print("\nTeams with lowest match rates:")
print(match_rate_by_team.head(20))
print("\nTeams with highest match rates:")
print(match_rate_by_team.tail(10))

[05/30/26 11:26:03] INFO     Saving cached data to /Users/fungs4/soccerdata/data/FBref               ]8;id=15495988;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=15495989;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py#250\250]8;;\

dlopen /usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework: dlopen(/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework, 0x0105): tried: '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file).

ENG-Premier League: 551 players

[05/30/26 11:26:09] INFO     Saving cached data to /Users/fungs4/soccerdata/data/FBref               ]8;id=15495994;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=15495995;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py#250\250]8;;\

dlopen /usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework: dlopen(/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework, 0x0105): tried: '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file).

ESP-La Liga: 611 players

[05/30/26 11:26:11] INFO     Saving cached data to /Users/fungs4/soccerdata/data/FBref               ]8;id=15496000;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=15496001;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py#250\250]8;;\

dlopen /usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework: dlopen(/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework, 0x0105): tried: '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file).

FRA-Ligue 1: 561 players

[05/30/26 11:26:15] INFO     Saving cached data to /Users/fungs4/soccerdata/data/FBref               ]8;id=15496006;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=15496007;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py#250\250]8;;\

dlopen /usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework: dlopen(/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework, 0x0105): tried: '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file).

GER-Bundesliga: 507 players

[05/30/26 11:26:19] INFO     Saving cached data to /Users/fungs4/soccerdata/data/FBref               ]8;id=15496012;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=15496013;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py#250\250]8;;\

dlopen /usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework: dlopen(/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework, 0x0105): tried: '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file).

ITA-Serie A: 609 players

[05/30/26 11:26:23] INFO     Saving cached data to /Users/fungs4/soccerdata/data/FBref               ]8;id=15496018;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=15496019;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py#250\250]8;;\

dlopen /usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework: dlopen(/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework, 0x0105): tried: '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file).

NED-Eredivisie: 550 players

[05/30/26 11:26:26] INFO     Saving cached data to /Users/fungs4/soccerdata/data/FBref               ]8;id=15496024;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=15496025;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py#250\250]8;;\

dlopen /usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework: dlopen(/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework, 0x0105): tried: '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file).

POR-Primeira Liga: 579 players

[05/30/26 11:26:30] INFO     Saving cached data to /Users/fungs4/soccerdata/data/FBref               ]8;id=15496030;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=15496031;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py#250\250]8;;\

dlopen /usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework: dlopen(/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework, 0x0105): tried: '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file).

SAU-Saudi Pro League: 555 players

[05/30/26 11:26:34] INFO     Saving cached data to /Users/fungs4/soccerdata/data/FBref               ]8;id=15496036;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=15496037;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py#250\250]8;;\

dlopen /usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework: dlopen(/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework, 0x0105): tried: '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file).

TUR-Super Lig: 600 players

[05/30/26 11:26:37] INFO     Saving cached data to /Users/fungs4/soccerdata/data/FBref               ]8;id=15496042;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=15496043;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py#250\250]8;;\

dlopen /usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework: dlopen(/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework, 0x0105): tried: '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file).

BEL-First Division A: 496 players

[05/30/26 11:27:04] INFO     Saving cached data to /Users/fungs4/soccerdata/data/FBref               ]8;id=15496048;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=15496049;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py#250\250]8;;\

dlopen /usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework: dlopen(/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework, 0x0105): tried: '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file).

SCO-Premiership: 389 players

[05/30/26 11:27:10] INFO     Saving cached data to /Users/fungs4/soccerdata/data/FBref               ]8;id=15496054;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=15496055;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py#250\250]8;;\

dlopen /usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework: dlopen(/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework, 0x0105): tried: '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file).

GRE-Super League: 466 players

[05/30/26 11:27:14] INFO     Saving cached data to /Users/fungs4/soccerdata/data/FBref               ]8;id=15496060;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=15496061;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py#250\250]8;;\

dlopen /usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework: dlopen(/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework, 0x0105): tried: '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file).

CZE-First League: 561 players

[05/30/26 11:27:17] INFO     Saving cached data to /Users/fungs4/soccerdata/data/FBref               ]8;id=15496066;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=15496067;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py#250\250]8;;\

dlopen /usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework: dlopen(/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework, 0x0105): tried: '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file).

AUT-Bundesliga: 344 players

[05/30/26 11:27:21] INFO     Saving cached data to /Users/fungs4/soccerdata/data/FBref               ]8;id=15496072;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=15496073;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py#250\250]8;;\

dlopen /usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework: dlopen(/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework, 0x0105): tried: '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file).

SUI-Super League: 387 players

[05/30/26 11:27:26] INFO     Saving cached data to /Users/fungs4/soccerdata/data/FBref               ]8;id=15496078;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=15496079;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py#250\250]8;;\

dlopen /usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework: dlopen(/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework, 0x0105): tried: '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file).

BRA-Serie A: 761 players

[05/30/26 11:27:31] INFO     Saving cached data to /Users/fungs4/soccerdata/data/FBref               ]8;id=15496084;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=15496085;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py#250\250]8;;\

dlopen /usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework: dlopen(/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework, 0x0105): tried: '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file).

ARG-Primera Division: 1069 players

[05/30/26 11:27:36] INFO     Saving cached data to /Users/fungs4/soccerdata/data/FBref               ]8;id=15496090;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=15496091;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py#250\250]8;;\

dlopen /usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework: dlopen(/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework, 0x0105): tried: '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file).

USA-MLS: 882 players

[05/30/26 11:27:41] INFO     Saving cached data to /Users/fungs4/soccerdata/data/FBref               ]8;id=15496096;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=15496097;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py#250\250]8;;\

dlopen /usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework: dlopen(/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework, 0x0105): tried: '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file).

MEX-Liga MX: 611 players

[05/30/26 11:27:45] INFO     Saving cached data to /Users/fungs4/soccerdata/data/FBref               ]8;id=15496102;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=15496103;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py#250\250]8;;\

dlopen /usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework: dlopen(/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework, 0x0105): tried: '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file).

KOR-K League 1: 440 players

[05/30/26 11:27:49] INFO     Saving cached data to /Users/fungs4/soccerdata/data/FBref               ]8;id=15496108;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=15496109;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py#250\250]8;;\

dlopen /usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework: dlopen(/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework, 0x0105): tried: '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file).

JPN-J1 League: 632 players

[05/30/26 11:27:54] INFO     Saving cached data to /Users/fungs4/soccerdata/data/FBref               ]8;id=15496114;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=15496115;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py#250\250]8;;\

dlopen /usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework: dlopen(/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework, 0x0105): tried: '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file).

ENG2-EFL Championship: 791 players

Total players: 12952
Matched: 816 (57.9%)
Unmatched: 594 (42.1%)

Teams with lowest match rates:
team
Qatar                     0.000000
South Africa              0.062500
Uzbekistan                0.066667
Jordan                    0.066667
IR Iran                   0.066667
Egypt                     0.111111
Iraq                      0.235294
Croatia                   0.269231
Bosnia and Herzegovina    0.269231
Panama                    0.304348
New Zealand               0.307692
Haiti                     0.384615
Saudi Arabia              0.400000
Czechia                   0.413793
Korea Republic            0.423077
Algeria                   0.444444
Morocco                   0.448276
Cabo Verde                0.461538
Tunisia                   0.500000
Curaçao                   0.500000
dtype: float64

Teams with highest match rates:
team
Austria        0.884615
Switzerland    0.884615
England        0.923077
Belgium        0.923077
USA            0.923077
Portugal       0.925926
Japan          0.925926
Netherlands    1.000000
Germany        1.000000
France         1.000000
dtype: float64

In [3]:
for lg in stats.index.get_level_values('league').unique():
    sub = stats.xs(lg, level='league')
    seasons = sub.index.get_level_values('season').unique().tolist()
    print(f"{lg}: {len(sub)} players, seasons={seasons}")

ENG-Premier League: 551 players, seasons=['2526']
ESP-La Liga: 611 players, seasons=['2526']
FRA-Ligue 1: 561 players, seasons=['2526']
GER-Bundesliga: 507 players, seasons=['2526']
ITA-Serie A: 609 players, seasons=['2526']
NED-Eredivisie: 550 players, seasons=['2526']
POR-Primeira Liga: 579 players, seasons=['2526']
SAU-Saudi Pro League: 555 players, seasons=['2526']
TUR-Super Lig: 600 players, seasons=['2526']
BEL-First Division A: 496 players, seasons=['2526']
SCO-Premiership: 389 players, seasons=['2526']
GRE-Super League: 466 players, seasons=['2526']
CZE-First League: 561 players, seasons=['2526']
AUT-Bundesliga: 344 players, seasons=['2526']
SUI-Super League: 387 players, seasons=['2526']
BRA-Serie A: 761 players, seasons=['2025']
ARG-Primera Division: 1069 players, seasons=['2025']
USA-MLS: 882 players, seasons=['2025']
MEX-Liga MX: 611 players, seasons=['2526']
KOR-K League 1: 440 players, seasons=['2025']
JPN-J1 League: 632 players, seasons=['2025']
ENG2-EFL Championship: 791 players, seasons=['2526']

## Data Merging

In [16]:
import unicodedata
from rapidfuzz import process, fuzz

def to_ascii(name):
    return unicodedata.normalize('NFKD', name).encode('ascii', 'ignore').decode().lower().strip()

# --- Flatten FBref MultiIndex columns ---
stats_flat = stats.copy()
stats_flat.columns = [
    f"{b}" if not a or a == b else f"{a}_{b}"
    for a, b in stats_flat.columns
]
stats_reset = stats_flat.reset_index()
stats_reset["name_ascii"] = stats_reset["player"].apply(to_ascii)

# --- WC players ---
wc_players = pd.read_csv("../data/processed/player_fixtures.csv")[
    ["player", "team", "position"]
].drop_duplicates()
wc_players["name_ascii"] = wc_players["player"].apply(to_ascii)

# --- Pass 1: exact ASCII match ---
fbref_ascii_set = set(stats_reset["name_ascii"])
exact_matched = wc_players[wc_players["name_ascii"].isin(fbref_ascii_set)].copy()
unmatched = wc_players[~wc_players["name_ascii"].isin(fbref_ascii_set)].copy()
print(f"Exact matches: {len(exact_matched)} | Unmatched: {len(unmatched)}")

# --- Pass 2: fuzzy match constrained by nationality ---
TEAM_TO_NATION = {
    "Algeria": "ALG", "Argentina": "ARG", "Australia": "AUS",
    "Austria": "AUT", "Belgium": "BEL", "Bosnia and Herzegovina": "BIH",
    "Brazil": "BRA", "Cabo Verde": "CPV", "Canada": "CAN", "Chile": "CHI",
    "Colombia": "COL", "Congo DR": "COD", "Costa Rica": "CRC",
    "Croatia": "CRO", "Curaçao": "CUW", "Côte d'Ivoire": "CIV",
    "Czechia": "CZE", "Ecuador": "ECU", "Egypt": "EGY", "England": "ENG",
    "France": "FRA", "Germany": "GER", "Ghana": "GHA", "Greece": "GRE",
    "Haiti": "HAI", "Honduras": "HON", "Hungary": "HUN", "IR Iran": "IRN",
    "Iraq": "IRQ", "Japan": "JPN", "Jordan": "JOR", "Kenya": "KEN",
    "Korea Republic": "KOR", "Mexico": "MEX", "Morocco": "MAR",
    "Netherlands": "NED", "New Zealand": "NZL", "Nigeria": "NGA",
    "Norway": "NOR", "Panama": "PAN", "Paraguay": "PAR", "Peru": "PER",
    "Poland": "POL", "Portugal": "POR", "Qatar": "QAT", "Romania": "ROU",
    "Saudi Arabia": "KSA", "Scotland": "SCO", "Senegal": "SEN",
    "Serbia": "SRB", "Slovakia": "SVK", "Slovenia": "SVN",
    "South Africa": "RSA", "Spain": "ESP", "Sweden": "SWE",
    "Switzerland": "SUI", "Trinidad and Tobago": "TRI", "Tunisia": "TUN",
    "Türkiye": "TUR", "Ukraine": "UKR", "Uruguay": "URU", "USA": "USA",
    "Uzbekistan": "UZB", "Venezuela": "VEN",
}

THRESHOLD = 85
KNOWN_FALSE_POSITIVES = {("Weverton", "Brazil")}

fbref_by_nation = stats_reset[["player", "name_ascii", "nation_"]].drop_duplicates()

fuzzy_rows = []
for _, row in unmatched.iterrows():
    nation_code = TEAM_TO_NATION.get(row["team"])
    if not nation_code:
        continue
    candidates = fbref_by_nation[fbref_by_nation["nation_"] == nation_code]
    if candidates.empty:
        continue
    result = process.extractOne(
        row["name_ascii"],
        candidates["name_ascii"].tolist(),
        scorer=fuzz.token_sort_ratio,
        score_cutoff=THRESHOLD,
    )
    if result and (row["player"], row["team"]) not in KNOWN_FALSE_POSITIVES:
        matched_ascii, score, _ = result
        fuzzy_rows.append({
            "player": row["player"],
            "team": row["team"],
            "position": row["position"],
            "name_ascii": matched_ascii,  # use FBref's ascii so the downstream merge works
        })

fuzzy_matched = pd.DataFrame(fuzzy_rows) if fuzzy_rows else pd.DataFrame(columns=exact_matched.columns)
print(f"Fuzzy matches: {len(fuzzy_matched)}")

matched_players = pd.concat([exact_matched, fuzzy_matched], ignore_index=True)
print(f"Total matched: {len(matched_players)} out of {len(wc_players)} WC players")

Exact matches: 936 | Unmatched: 518
Fuzzy matches: 49
Total matched: 985 out of 1454 WC players

In [17]:
matched_players.head(10)

             player     team position        name_ascii
0   Rayan Aït-Nouri  Algeria      DEF   rayan ait-nouri
1   Ramy Bensebaini  Algeria      DEF   ramy bensebaini
2       Aïssa Mandi  Algeria      DEF       aissa mandi
3    Rafik Belghali  Algeria      DEF    rafik belghali
4      Amine Gouiri  Algeria      FWD      amine gouiri
5      Riyad Mahrez  Algeria      MID      riyad mahrez
6      Ibrahim Maza  Algeria      FWD      ibrahim maza
7  Anis Hadj Moussa  Algeria      FWD  anis hadj moussa
8    Ramiz Zerrouki  Algeria      MID    ramiz zerrouki
9   Hicham Boudaoui  Algeria      MID   hicham boudaoui

Now, we just want to explore the 456 unmatched players

In [18]:
unmatched_final = wc_players[
    ~wc_players["player"].isin(matched_players["player"])
][["player", "team", "position"]].sort_values(["team", "position"]).reset_index(drop=True)

print(f"Unmatched players: {len(unmatched_final)}")
print(unmatched_final.to_string())

Unmatched players: 469
                          player                    team position
0                   Mehdi Dorval                 Algeria      DEF
1               Zinéddine Belaïd                 Algeria      DEF
2                    Sohaib Nair                 Algeria      DEF
3                   Achref Abada                 Algeria      DEF
4                Farès Ghedjemis                 Algeria      FWD
5                Ahmed Benbouali                 Algeria      FWD
6                   Amin Chiakha                 Algeria      FWD
7                Anthony Mandréa                 Algeria       GK
8                    Luca Zidane                 Algeria       GK
9                  Melvin Mastil                 Algeria       GK
10              Kilian Belazzoug                 Algeria       GK
11                 Adil Boulbina                 Algeria      MID
12              Santiago Beltrán               Argentina       GK
13                      Nico Paz               Argentina      MID
14              Emiliano Buendía               Argentina      MID
15                  Tomás Aranda               Argentina      MID
16                    Jordan Bos               Australia      DEF
17                 Milos Degenek               Australia      DEF
18                   Aziz Behich               Australia      DEF
19                  Fran Karacic               Australia      DEF
20                    Kai Trewin               Australia      DEF
21              Lucas Herrington               Australia      DEF
22             Nishan Velupillay               Australia      FWD
23                    Deni Juric               Australia      FWD
24              Brandon Borrello               Australia      FWD
25                     Paul Izzo               Australia       GK
26                 Patrick Beach               Australia       GK
27                     Joe Gauci               Australia       GK
28                     Paul Okon               Australia      MID
29                Alex Robertson               Australia      MID
30                    Awer Mabil               Australia      MID
31                Cameron Devlin               Australia      MID
32                 Mathew Leckie               Australia      MID
33               Michael Svoboda                 Austria      DEF
34              Marko Arnautovic                 Austria      FWD
35                 Patrick Pentz                 Austria       GK
36                  Nikola Katic  Bosnia and Herzegovina      DEF
37              Stjepan Radeljic  Bosnia and Herzegovina      DEF
38           Dennis Hadzikadunic  Bosnia and Herzegovina      DEF
39                    Jovo Lukic  Bosnia and Herzegovina      FWD
40                  Samed Bazdar  Bosnia and Herzegovina      FWD
41                Osman Hadzikic  Bosnia and Herzegovina       GK
42              Martin Zlomislic  Bosnia and Herzegovina       GK
43                 Dzenis Burnic  Bosnia and Herzegovina      MID
44                   Ivan Sunjic  Bosnia and Herzegovina      MID
45                    Ivan Basic  Bosnia and Herzegovina      MID
46            Benjamin Tahirovic  Bosnia and Herzegovina      MID
47                        Ibañez                  Brazil      DEF
48                Douglas Santos                  Brazil      DEF
49                        Bremer                  Brazil      DEF
50                Alisson Becker                  Brazil       GK
51                          Pico              Cabo Verde      DEF
52                  Kelvin Pires              Cabo Verde      DEF
53                         Diney              Cabo Verde      DEF
54                       Stopira              Cabo Verde      DEF
55               Garry Rodrigues              Cabo Verde      FWD
56                  Willy Semedo              Cabo Verde      FWD
57                       Vozinha              Cabo Verde       GK
58                 CJ dos Santos              Cabo Verde       GK
59                Márcio da Rosa              Cabo Verde       GK
60                Yannick Semedo              Cabo Verde      MID
61                    Kevin Pina              Cabo Verde      MID
62                  Deroy Duarte              Cabo Verde      MID
63                  Laros Duarte              Cabo Verde      MID
64              Gilson Benchimol              Cabo Verde      MID
65            Jamie Knight-Lebel                  Canada      DEF
66                  Owen Goodman                  Canada       GK
67                   Ralph Priso                  Canada      MID
68                    Niko Sigur                  Canada      MID
69               Cucho Hernández                Colombia      FWD
70                  David Ospina                Colombia       GK
71                Álvaro Montero                Colombia       GK
72                Gustavo Puerta                Colombia      MID
73        Juan Fernando Quintero                Colombia      MID
74                 Juan Portilla                Colombia      MID
75                 Steve Kapuadi                Congo DR      DEF
76                 Gédéon Kalulu                Congo DR      DEF
77                   Simon Banza                Congo DR      FWD
78                 Fiston Mayele                Congo DR      FWD
79               Nathanaël Mbuku                Congo DR      FWD
80                 Brian Cipenga                Congo DR      FWD
81                Timothy Fayulu                Congo DR       GK
82                 Théo Bongonda                Congo DR      MID
83                  Martin Erlic                 Croatia      DEF
84              Dominik Kotarski                 Croatia       GK
85                     Toni Fruk                 Croatia      MID
86                Leandro Bacuna                 Curaçao      DEF
87              Roshon van Eijma                 Curaçao      DEF
88                Ar'Jany Martha                 Curaçao      DEF
89                  Juriën Gaari                 Curaçao      DEF
90                   Kenji Gorré                 Curaçao      FWD
91              Jearl Margaritha                 Curaçao      FWD
92             Gervane Kastaneer                 Curaçao      FWD
93                Jürgen Locadia                 Curaçao      FWD
94                     Eloy Room                 Curaçao       GK
95             Trevor Doornbusch                 Curaçao       GK
96                  Tyrick Bodak                 Curaçao       GK
97           Godfried Roemeratoe                 Curaçao      MID
98                  Kevin Felida                 Curaçao      MID
99                   Evan Ndicka           Côte d'Ivoire      DEF
100            Jean Michaël Seri           Côte d'Ivoire      MID
101                 Félix Torres                 Ecuador      DEF
102              Deinner Ordóñez                 Ecuador      DEF
103               Fricio Caicedo                 Ecuador      DEF
104                Jordy Caicedo                 Ecuador      FWD
105                Gonzalo Valle                 Ecuador       GK
106               Cristhian Loor                 Ecuador       GK
107               Denil Castillo                 Ecuador      MID
108                Jordy Alcívar                 Ecuador      MID
109                  John Yeboah                 Ecuador      MID
110             Ederson Castillo                 Ecuador      MID
111                Darwin Guagua                 Ecuador      MID
112               Malcom DaCosta                 Ecuador      MID
113                Bruno Caicedo                 Ecuador      MID
114                 Luis Fragozo                 Ecuador      MID
115           Mohamed Abdelmonem                   Egypt      DEF
116                 Ahmed Fatouh                   Egypt      DEF
117                 Mohamed Hany                   Egypt      DEF
118                   Ramy Rabia                   Egypt      DEF
119           Hossam Abdelmaguid                   Egypt      DEF
120                   Tarek Alaa                   Egypt      DEF
121               Yasser Ibrahim                   Egypt      DEF
122                  Karim Hafez                   Egypt      DEF
123                    Trezeguet                   Egypt      FWD
124               Aqtay Abdallah                   Egypt      FWD
125             Hamza Abdelkarim                   Egypt      FWD
126           Mohamed El Shenawy                   Egypt       GK
127             El Mahdy Soliman                   Egypt       GK
128              Mostafa Shobeir                   Egypt       GK
129                 Mohamed Alaa                   Egypt       GK
130                 Marwan Attia                   Egypt      MID
131                         Zizo                   Egypt      MID
132                  Hamdi Fathy                   Egypt      MID
133                  Emam Ashour                   Egypt      MID
134                Mahmoud Saber                   Egypt      MID
135              Mohanad Lasheen                   Egypt      MID
136                 Ibrahim Adel                   Egypt      MID
137             Nabil Emad Dunga                   Egypt      MID
138                 Mostafa Zico                   Egypt      MID
139                   Abdul Baba                   Ghana      DEF
140                   Prince Adu                   Ghana      FWD
141                 Abdul Fatawu                   Ghana      FWD
142       Christopher Bonsu Baah                   Ghana      FWD
143               Benjamin Asare                   Ghana       GK
144                Paul Reverson                   Ghana       GK
145               Solomon Agbasi                   Ghana       GK
146            Lawrence Ati Zigi                   Ghana       GK
147                 Joseph Anang                   Ghana       GK
148             Augustine Boakye                   Ghana      MID
149               Caleb Yirenkyi                   Ghana      MID
150                  Ricardo Adé                   Haiti      DEF
151            Martin Expérience                   Haiti      DEF
152                 Duke Lacroix                   Haiti      DEF
153              Keeto Thermoncy                   Haiti      DEF
154                Duckens Nazon                   Haiti      FWD
155               Yassin Fortuné                   Haiti      FWD
156             Ruben Providence                   Haiti      FWD
157                 Lenny Joseph                   Haiti      FWD
158                Johny Placide                   Haiti       GK
159             Alexandre Pierre                   Haiti       GK
160               Josué Duverger                   Haiti       GK
161             Woodensky Pierre                   Haiti      MID
162              Leverton Pierre                   Haiti      MID
163                  Carl Sainté                   Haiti      MID
164          Danley Jean Jacques                   Haiti      MID
165               Ramin Rezaeian                 IR Iran      DEF
166               Hossein Kanani                 IR Iran      DEF
167              Milad Mohammadi                 IR Iran      DEF
168            Shoja Khalilzadeh                 IR Iran      DEF
169               Ehsan Hajisafi                 IR Iran      DEF
170                Saleh Hardani                 IR Iran      DEF
171                   Ali Nemati                 IR Iran      DEF
172                 Aria Yousefi                 IR Iran      DEF
173                  Danial Eiri                 IR Iran      DEF
174                Saman Ghoddos                 IR Iran      FWD
175                  Ali Alipour                 IR Iran      FWD
176               Dennis Dargahi                 IR Iran      FWD
177     Amirhossein Hosseinzadeh                 IR Iran      FWD
178         Amirhossein Mahmoudi                 IR Iran      FWD
179                 Kasra Taheri                 IR Iran      FWD
180           Alireza Beiranvand                 IR Iran       GK
181               Payam Niazmand                 IR Iran       GK
182             Hossein Hosseini                 IR Iran       GK
183            Mohammad Khalifeh                 IR Iran       GK
184    Amir Mohammad Razzaghinia                 IR Iran      MID
185             Hadi Habibinejad                 IR Iran      MID
186            Mohammad Ghorbani                 IR Iran      MID
187               Omid Noorafkan                 IR Iran      MID
188                 Mehdi Torabi                 IR Iran      MID
189              Saeid Ezatolahi                 IR Iran      MID
190              Mohammad Mohebi                 IR Iran      MID
191                Mehdi Ghayedi                 IR Iran      MID
192              Roozbeh Cheshmi                 IR Iran      MID
193                 Frans Putros                    Iraq      DEF
194                 Rebin Sulaka                    Iraq      DEF
195               Maytham Jabbar                    Iraq      DEF
196                  Hussein Ali                    Iraq      DEF
197                 Zaid Tahseen                    Iraq      DEF
198                 Munaf Younus                    Iraq      DEF
199                  Akam Hashim                    Iraq      DEF
200                 Ahmed Maknzi                    Iraq      DEF
201              Mustafa Saadoon                    Iraq      DEF
202                  Ahmed Yahya                    Iraq      DEF
203                Aymen Hussein                    Iraq      FWD
204                  Mohanad Ali                    Iraq      FWD
205                 Youssef Amyn                    Iraq      FWD
206                   Ali Yousif                    Iraq      FWD
207                  Ahmed Basil                    Iraq       GK
208                  Fahad Talib                    Iraq       GK
209                  Kumel Saadi                    Iraq       GK
210                 Jalal Hassan                    Iraq       GK
211                  Zaid Ismael                    Iraq      MID
212                  Marko Farji                    Iraq      MID
213            Hasan Abdulkareem                    Iraq      MID
214                Peter Gwargis                    Iraq      MID
215                  Kevin Yakob                    Iraq      MID
216               Amir Al Ammari                    Iraq      MID
217                   Aimar Sher                    Iraq      MID
218                 Karar Nabeel                    Iraq      MID
219               Keito Nakamura                   Japan      MID
220               Abdallah Nasib                  Jordan      DEF
221            Mohannad Abu Taha                  Jordan      DEF
222        Mohammad Abu Hasheesh                  Jordan      DEF
223           Husam Abu Al Dahab                  Jordan      DEF
224                Mohammad Taha                  Jordan      DEF
225                  Ahmad Assaf                  Jordan      DEF
226                 Saleem Obaid                  Jordan      DEF
227         Mohammad Abu Al Nadi                  Jordan      DEF
228                  Amer Jamous                  Jordan      DEF
229                 Ehsan Haddad                  Jordan      DEF
230                Saed Al Rosan                  Jordan      DEF
231                  Anas Badawi                  Jordan      DEF
232              Mousa Al Tamari                  Jordan      FWD
233           Mohammad Abu Zraiq                  Jordan      FWD
234             Mahmoud Al Mardi                  Jordan      FWD
235                Odeh Fakhoury                  Jordan      FWD
236                    Ali Olwan                  Jordan      FWD
237             Yazeed  Abulaila                  Jordan       GK
238         Abdallah Al Fakhouri                  Jordan       GK
239             Nour Bani Ateyah                  Jordan       GK
240              Ahmad Al Juaidi                  Jordan       GK
241                 Yousef Qashi                  Jordan      MID
242                Ibrahim Sadeh                  Jordan      MID
243            Mohammad Al Daoud                  Jordan      MID
244             Noor Al Rawabdeh                  Jordan      MID
245             Nizar Al Rashdan                  Jordan      MID
246                 Raja'ei Ayed                  Jordan      MID
247               Seol Young-Woo          Korea Republic      DEF
248                   Cho Yu-Min          Korea Republic      DEF
249                 Lee Han-Beom          Korea Republic      DEF
250                 Cho Gue-Sung          Korea Republic      FWD
251                 César Montes                  Mexico      DEF
252                Jorge Sánchez                  Mexico      DEF
253               Everardo López                  Mexico      DEF
254              Guillermo Ochoa                  Mexico       GK
255                  Raúl Rangel                  Mexico       GK
256                  Luis Chávez                  Mexico      MID
257                 Ismaël Baouf                 Morocco      DEF
258            Youssef Belammari                 Morocco      DEF
259            Soufiane Bouftini                 Morocco      DEF
260                Mohamed Chibi                 Morocco      DEF
261  Ayoube Amaimouni-Echghouyab                 Morocco      FWD
262            Soufiane Benjdida                 Morocco      FWD
263              Tawfik Bentayeb                 Morocco      FWD
264                   Amine Sbaï                 Morocco      FWD
265              Soufiane Rahimi                 Morocco      FWD
266           El Mehdi Al Harrar                 Morocco       GK
267              Munir El Kajoui                 Morocco       GK
268                Ibrahim Gomis                 Morocco       GK
269             Yanis Benchaouch                 Morocco       GK
270              Ahmed Tagnaouti                 Morocco       GK
271           Soufiane El-Faouzi                 Morocco      MID
272                Memphis Depay             Netherlands      FWD
273             Francis de Vries             New Zealand      DEF
274                    Tim Payne             New Zealand      DEF
275                Callan Elliot             New Zealand      DEF
276               Nando Pijnaker             New Zealand      DEF
277                  Tommy Smith             New Zealand      DEF
278            Kosta Barbarouses             New Zealand      FWD
279                    Ben Waine             New Zealand      FWD
280                      Ben Old             New Zealand      FWD
281                Jesse Randall             New Zealand      FWD
282              Matthew Garbett             New Zealand      FWD
283                 Alex Paulsen             New Zealand       GK
284                 Michael Woud             New Zealand       GK
285              Callum McCowatt             New Zealand      MID
286                   Alex Rufer             New Zealand      MID
287                     Joe Bell             New Zealand      MID
288                  Elijah Just             New Zealand      MID
289              Lachlan Bayliss             New Zealand      MID
290               Sarpreet Singh             New Zealand      MID
291                 Leo Østigård                  Norway      DEF
292              Fredrik Bjørkan                  Norway      DEF
293             Henrik Falchener                  Norway      DEF
294                 Patrick Berg                  Norway      MID
295            Jens Petter Hauge                  Norway      MID
296                 Amir Murillo                  Panama      DEF
297                   Éric Davis                  Panama      DEF
298               César Blackman                  Panama      DEF
299               Andrés Andrade                  Panama      DEF
300              Roderick Miller                  Panama      DEF

Manual Mapping

In [19]:
# Pass 3: manual overrides
import sys, os
sys.path.insert(0, os.path.abspath(".."))
from data.manual_overrides import MANUAL_OVERRIDES


still_unmatched = wc_players[~wc_players["player"].isin(matched_players["player"])].copy()

override_rows = []
for _, row in still_unmatched.iterrows():
    fbref_name = MANUAL_OVERRIDES.get(row["player"])
    if fbref_name:
        fbref_ascii = to_ascii(fbref_name)
        override_rows.append({
            "player": row["player"],
            "team": row["team"],
            "position": row["position"],
            "name_ascii": fbref_ascii,
        })

override_matched = pd.DataFrame(override_rows) if override_rows else pd.DataFrame(columns=matched_players.columns)
print(f"Manual override matches: {len(override_matched)}")

matched_players = pd.concat([matched_players, override_matched], ignore_index=True)
print(f"Total matched: {len(matched_players)} / {len(wc_players)} WC players")

Manual override matches: 33
Total matched: 1018 / 1454 WC players

In [20]:
unmatched_final = wc_players[
    ~wc_players["player"].isin(matched_players["player"])
][["player", "team", "position"]].sort_values(["team", "position"]).reset_index(drop=True)

print(f"Unmatched players: {len(unmatched_final)}")
print(unmatched_final.to_string())

Unmatched players: 436
                        player                    team position
0                 Mehdi Dorval                 Algeria      DEF
1             Zinéddine Belaïd                 Algeria      DEF
2                  Sohaib Nair                 Algeria      DEF
3                 Achref Abada                 Algeria      DEF
4              Farès Ghedjemis                 Algeria      FWD
5              Ahmed Benbouali                 Algeria      FWD
6                 Amin Chiakha                 Algeria      FWD
7              Anthony Mandréa                 Algeria       GK
8                  Luca Zidane                 Algeria       GK
9                Melvin Mastil                 Algeria       GK
10            Kilian Belazzoug                 Algeria       GK
11               Adil Boulbina                 Algeria      MID
12            Santiago Beltrán               Argentina       GK
13                Tomás Aranda               Argentina      MID
14               Milos Degenek               Australia      DEF
15                 Aziz Behich               Australia      DEF
16                Fran Karacic               Australia      DEF
17                  Kai Trewin               Australia      DEF
18            Lucas Herrington               Australia      DEF
19           Nishan Velupillay               Australia      FWD
20                  Deni Juric               Australia      FWD
21            Brandon Borrello               Australia      FWD
22                   Paul Izzo               Australia       GK
23               Patrick Beach               Australia       GK
24                   Joe Gauci               Australia       GK
25                   Paul Okon               Australia      MID
26              Alex Robertson               Australia      MID
27                  Awer Mabil               Australia      MID
28              Cameron Devlin               Australia      MID
29               Mathew Leckie               Australia      MID
30             Michael Svoboda                 Austria      DEF
31            Marko Arnautovic                 Austria      FWD
32               Patrick Pentz                 Austria       GK
33                Nikola Katic  Bosnia and Herzegovina      DEF
34            Stjepan Radeljic  Bosnia and Herzegovina      DEF
35         Dennis Hadzikadunic  Bosnia and Herzegovina      DEF
36                  Jovo Lukic  Bosnia and Herzegovina      FWD
37                Samed Bazdar  Bosnia and Herzegovina      FWD
38              Osman Hadzikic  Bosnia and Herzegovina       GK
39            Martin Zlomislic  Bosnia and Herzegovina       GK
40               Dzenis Burnic  Bosnia and Herzegovina      MID
41                 Ivan Sunjic  Bosnia and Herzegovina      MID
42                  Ivan Basic  Bosnia and Herzegovina      MID
43          Benjamin Tahirovic  Bosnia and Herzegovina      MID
44              Douglas Santos                  Brazil      DEF
45                        Pico              Cabo Verde      DEF
46                Kelvin Pires              Cabo Verde      DEF
47                       Diney              Cabo Verde      DEF
48                     Stopira              Cabo Verde      DEF
49             Garry Rodrigues              Cabo Verde      FWD
50                Willy Semedo              Cabo Verde      FWD
51                     Vozinha              Cabo Verde       GK
52               CJ dos Santos              Cabo Verde       GK
53              Márcio da Rosa              Cabo Verde       GK
54              Yannick Semedo              Cabo Verde      MID
55                  Kevin Pina              Cabo Verde      MID
56                Deroy Duarte              Cabo Verde      MID
57                Laros Duarte              Cabo Verde      MID
58            Gilson Benchimol              Cabo Verde      MID
59          Jamie Knight-Lebel                  Canada      DEF
60                Owen Goodman                  Canada       GK
61                  Niko Sigur                  Canada      MID
62                David Ospina                Colombia       GK
63              Álvaro Montero                Colombia       GK
64              Gustavo Puerta                Colombia      MID
65      Juan Fernando Quintero                Colombia      MID
66               Juan Portilla                Colombia      MID
67               Steve Kapuadi                Congo DR      DEF
68               Gédéon Kalulu                Congo DR      DEF
69                 Simon Banza                Congo DR      FWD
70               Fiston Mayele                Congo DR      FWD
71             Nathanaël Mbuku                Congo DR      FWD
72               Brian Cipenga                Congo DR      FWD
73              Timothy Fayulu                Congo DR       GK
74               Théo Bongonda                Congo DR      MID
75                Martin Erlic                 Croatia      DEF
76            Dominik Kotarski                 Croatia       GK
77                   Toni Fruk                 Croatia      MID
78              Leandro Bacuna                 Curaçao      DEF
79            Roshon van Eijma                 Curaçao      DEF
80              Ar'Jany Martha                 Curaçao      DEF
81                Juriën Gaari                 Curaçao      DEF
82                 Kenji Gorré                 Curaçao      FWD
83            Jearl Margaritha                 Curaçao      FWD
84           Gervane Kastaneer                 Curaçao      FWD
85              Jürgen Locadia                 Curaçao      FWD
86                   Eloy Room                 Curaçao       GK
87           Trevor Doornbusch                 Curaçao       GK
88                Tyrick Bodak                 Curaçao       GK
89         Godfried Roemeratoe                 Curaçao      MID
90                Kevin Felida                 Curaçao      MID
91           Jean Michaël Seri           Côte d'Ivoire      MID
92                Félix Torres                 Ecuador      DEF
93             Deinner Ordóñez                 Ecuador      DEF
94              Fricio Caicedo                 Ecuador      DEF
95               Jordy Caicedo                 Ecuador      FWD
96               Gonzalo Valle                 Ecuador       GK
97              Cristhian Loor                 Ecuador       GK
98              Denil Castillo                 Ecuador      MID
99               Jordy Alcívar                 Ecuador      MID
100                John Yeboah                 Ecuador      MID
101           Ederson Castillo                 Ecuador      MID
102              Darwin Guagua                 Ecuador      MID
103             Malcom DaCosta                 Ecuador      MID
104              Bruno Caicedo                 Ecuador      MID
105               Luis Fragozo                 Ecuador      MID
106         Mohamed Abdelmonem                   Egypt      DEF
107               Ahmed Fatouh                   Egypt      DEF
108               Mohamed Hany                   Egypt      DEF
109                 Ramy Rabia                   Egypt      DEF
110         Hossam Abdelmaguid                   Egypt      DEF
111                 Tarek Alaa                   Egypt      DEF
112             Yasser Ibrahim                   Egypt      DEF
113                Karim Hafez                   Egypt      DEF
114                  Trezeguet                   Egypt      FWD
115             Aqtay Abdallah                   Egypt      FWD
116           Hamza Abdelkarim                   Egypt      FWD
117         Mohamed El Shenawy                   Egypt       GK
118           El Mahdy Soliman                   Egypt       GK
119            Mostafa Shobeir                   Egypt       GK
120               Mohamed Alaa                   Egypt       GK
121               Marwan Attia                   Egypt      MID
122                       Zizo                   Egypt      MID
123                Hamdi Fathy                   Egypt      MID
124                Emam Ashour                   Egypt      MID
125              Mahmoud Saber                   Egypt      MID
126            Mohanad Lasheen                   Egypt      MID
127               Ibrahim Adel                   Egypt      MID
128               Mostafa Zico                   Egypt      MID
129                 Abdul Baba                   Ghana      DEF
130               Abdul Fatawu                   Ghana      FWD
131             Benjamin Asare                   Ghana       GK
132              Paul Reverson                   Ghana       GK
133             Solomon Agbasi                   Ghana       GK
134               Joseph Anang                   Ghana       GK
135           Augustine Boakye                   Ghana      MID
136             Caleb Yirenkyi                   Ghana      MID
137                Ricardo Adé                   Haiti      DEF
138          Martin Expérience                   Haiti      DEF
139               Duke Lacroix                   Haiti      DEF
140            Keeto Thermoncy                   Haiti      DEF
141              Duckens Nazon                   Haiti      FWD
142             Yassin Fortuné                   Haiti      FWD
143           Ruben Providence                   Haiti      FWD
144               Lenny Joseph                   Haiti      FWD
145              Johny Placide                   Haiti       GK
146           Alexandre Pierre                   Haiti       GK
147             Josué Duverger                   Haiti       GK
148           Woodensky Pierre                   Haiti      MID
149            Leverton Pierre                   Haiti      MID
150                Carl Sainté                   Haiti      MID
151             Ramin Rezaeian                 IR Iran      DEF
152             Hossein Kanani                 IR Iran      DEF
153            Milad Mohammadi                 IR Iran      DEF
154          Shoja Khalilzadeh                 IR Iran      DEF
155             Ehsan Hajisafi                 IR Iran      DEF
156              Saleh Hardani                 IR Iran      DEF
157                 Ali Nemati                 IR Iran      DEF
158               Aria Yousefi                 IR Iran      DEF
159                Danial Eiri                 IR Iran      DEF
160              Saman Ghoddos                 IR Iran      FWD
161                Ali Alipour                 IR Iran      FWD
162             Dennis Dargahi                 IR Iran      FWD
163   Amirhossein Hosseinzadeh                 IR Iran      FWD
164       Amirhossein Mahmoudi                 IR Iran      FWD
165               Kasra Taheri                 IR Iran      FWD
166         Alireza Beiranvand                 IR Iran       GK
167             Payam Niazmand                 IR Iran       GK
168           Hossein Hosseini                 IR Iran       GK
169          Mohammad Khalifeh                 IR Iran       GK
170  Amir Mohammad Razzaghinia                 IR Iran      MID
171           Hadi Habibinejad                 IR Iran      MID
172          Mohammad Ghorbani                 IR Iran      MID
173             Omid Noorafkan                 IR Iran      MID
174               Mehdi Torabi                 IR Iran      MID
175            Saeid Ezatolahi                 IR Iran      MID
176            Mohammad Mohebi                 IR Iran      MID
177              Mehdi Ghayedi                 IR Iran      MID
178            Roozbeh Cheshmi                 IR Iran      MID
179               Frans Putros                    Iraq      DEF
180               Rebin Sulaka                    Iraq      DEF
181             Maytham Jabbar                    Iraq      DEF
182                Hussein Ali                    Iraq      DEF
183               Zaid Tahseen                    Iraq      DEF
184               Munaf Younus                    Iraq      DEF
185                Akam Hashim                    Iraq      DEF
186               Ahmed Maknzi                    Iraq      DEF
187            Mustafa Saadoon                    Iraq      DEF
188                Ahmed Yahya                    Iraq      DEF
189              Aymen Hussein                    Iraq      FWD
190                Mohanad Ali                    Iraq      FWD
191               Youssef Amyn                    Iraq      FWD
192                 Ali Yousif                    Iraq      FWD
193                Ahmed Basil                    Iraq       GK
194                Fahad Talib                    Iraq       GK
195                Kumel Saadi                    Iraq       GK
196               Jalal Hassan                    Iraq       GK
197                Zaid Ismael                    Iraq      MID
198                Marko Farji                    Iraq      MID
199          Hasan Abdulkareem                    Iraq      MID
200              Peter Gwargis                    Iraq      MID
201                Kevin Yakob                    Iraq      MID
202             Amir Al Ammari                    Iraq      MID
203                 Aimar Sher                    Iraq      MID
204               Karar Nabeel                    Iraq      MID
205             Keito Nakamura                   Japan      MID
206             Abdallah Nasib                  Jordan      DEF
207          Mohannad Abu Taha                  Jordan      DEF
208      Mohammad Abu Hasheesh                  Jordan      DEF
209         Husam Abu Al Dahab                  Jordan      DEF
210              Mohammad Taha                  Jordan      DEF
211                Ahmad Assaf                  Jordan      DEF
212               Saleem Obaid                  Jordan      DEF
213       Mohammad Abu Al Nadi                  Jordan      DEF
214                Amer Jamous                  Jordan      DEF
215               Ehsan Haddad                  Jordan      DEF
216              Saed Al Rosan                  Jordan      DEF
217                Anas Badawi                  Jordan      DEF
218         Mohammad Abu Zraiq                  Jordan      FWD
219           Mahmoud Al Mardi                  Jordan      FWD
220              Odeh Fakhoury                  Jordan      FWD
221                  Ali Olwan                  Jordan      FWD
222           Yazeed  Abulaila                  Jordan       GK
223       Abdallah Al Fakhouri                  Jordan       GK
224           Nour Bani Ateyah                  Jordan       GK
225            Ahmad Al Juaidi                  Jordan       GK
226               Yousef Qashi                  Jordan      MID
227              Ibrahim Sadeh                  Jordan      MID
228          Mohammad Al Daoud                  Jordan      MID
229           Noor Al Rawabdeh                  Jordan      MID
230           Nizar Al Rashdan                  Jordan      MID
231               Raja'ei Ayed                  Jordan      MID
232             Seol Young-Woo          Korea Republic      DEF
233                 Cho Yu-Min          Korea Republic      DEF
234               Lee Han-Beom          Korea Republic      DEF
235               Cho Gue-Sung          Korea Republic      FWD
236               César Montes                  Mexico      DEF
237             Everardo López                  Mexico      DEF
238            Guillermo Ochoa                  Mexico       GK
239                Raúl Rangel                  Mexico       GK
240                Luis Chávez                  Mexico      MID
241               Ismaël Baouf                 Morocco      DEF
242          Youssef Belammari                 Morocco      DEF
243          Soufiane Bouftini                 Morocco      DEF
244              Mohamed Chibi                 Morocco      DEF
245          Soufiane Benjdida                 Morocco      FWD
246            Tawfik Bentayeb                 Morocco      FWD
247                 Amine Sbaï                 Morocco      FWD
248            Soufiane Rahimi                 Morocco      FWD
249         El Mehdi Al Harrar                 Morocco       GK
250            Munir El Kajoui                 Morocco       GK
251              Ibrahim Gomis                 Morocco       GK
252           Yanis Benchaouch                 Morocco       GK
253            Ahmed Tagnaouti                 Morocco       GK
254         Soufiane El-Faouzi                 Morocco      MID
255              Memphis Depay             Netherlands      FWD
256           Francis de Vries             New Zealand      DEF
257                  Tim Payne             New Zealand      DEF
258              Callan Elliot             New Zealand      DEF
259             Nando Pijnaker             New Zealand      DEF
260                Tommy Smith             New Zealand      DEF
261          Kosta Barbarouses             New Zealand      FWD
262                  Ben Waine             New Zealand      FWD
263                    Ben Old             New Zealand      FWD
264              Jesse Randall             New Zealand      FWD
265            Matthew Garbett             New Zealand      FWD
266               Alex Paulsen             New Zealand       GK
267               Michael Woud             New Zealand       GK
268            Callum McCowatt             New Zealand      MID
269                 Alex Rufer             New Zealand      MID
270                   Joe Bell             New Zealand      MID
271            Lachlan Bayliss             New Zealand      MID
272             Sarpreet Singh             New Zealand      MID
273            Fredrik Bjørkan                  Norway      DEF
274           Henrik Falchener                  Norway      DEF
275               Patrick Berg                  Norway      MID
276          Jens Petter Hauge                  Norway      MID
277                 Éric Davis                  Panama      DEF
278             César Blackman                  Panama      DEF
279            Roderick Miller                  Panama      DEF
280              Jiovany Ramos                  Panama      DEF
281                Martín Krug                  Panama      DEF
282            Jorge Gutiérrez                  Panama      DEF
283              Fidel Escobar                  Panama      DEF
284             Edgardo Fariña                  Panama      DEF
285               José Fajardo                  Panama      FWD
286           Cecilio Waterman                  Panama      FWD
287                César Yanis                  Panama      FWD
288           Alberto Quintero                  Panama      FWD
289            Azarías Londoño                  Panama      FWD
290            Tomás Rodríguez                  Panama      FWD
291                 Luis Mejía                  Panama       GK
292              César Samudio                  Panama       GK
293          Cristian Martínez                  Panama      MID
294          Gustavo Velázquez                Paraguay      DEF
295          Juan José Cáceres                Paraguay      DEF
296            Alcides Benítez                Paraguay      DEF
297                 Diego León                Paraguay      DEF
298          Alexandro Maidana                Paraguay      FWD
299            Carlos González                Paraguay      FWD
300             Adrián Alcaraz                Paraguay      FWD
301             Gastón Olveira                Paraguay       GK
302             Santiago Rojas                Paraguay       GK
303   Maurício Magalhães Prado                Paraguay      MID
304           Alejandro Romero                Paraguay      MID
305      Robert Piris Da Motta                Paraguay      MID
306                Hugo Cuenca                Paraguay      MID
307           Álvaro Campuzano                Paraguay      MID
308               Rodney Redes                Paraguay      MID
309              Enso González                Paraguay      MID
310          Lorenzo Melgarejo                Paraguay      MID

Here, we merge the `matched_players` dataframe with the relevant FBRef data

In [21]:
import numpy as np

# Step 1: Merge with league included
merged = matched_players.merge(
    stats_reset[[
        "name_ascii", "league", "pos_",
        "Playing Time_Min",
        "Per 90 Minutes_G-PK", "Per 90 Minutes_Ast", "Per 90 Minutes_G+A"
    ]],
    on="name_ascii",
    how="left"
).rename(columns={
    "pos_": "fbref_pos",
    "Playing Time_Min": "minutes",
    "Per 90 Minutes_G-PK": "gls_p90",
    "Per 90 Minutes_Ast": "ast_p90",
    "Per 90 Minutes_G+A": "ga_p90"
})

# Step 2: Apply minimum minutes filter
MIN_MINS = 900
merged_filtered = merged[merged["minutes"] >= MIN_MINS].copy()
print(f"Players after {MIN_MINS} min filter: {len(merged_filtered)}")

Players after 900 min filter: 912

In [14]:
merged_filtered.head()

,player,team,position,name_ascii,league,fbref_pos,minutes,gls_p90,ast_p90,ga_p90
0,Rayan Aït-Nouri,Algeria,DEF,rayan ait-nouri,ENG-Premier League,DF,974,0.0,0.18,0.18
1,Ramy Bensebaini,Algeria,DEF,ramy bensebaini,GER-Bundesliga,DF,1530,0.18,0.12,0.41
2,Aïssa Mandi,Algeria,DEF,aissa mandi,FRA-Ligue 1,DF,2424,0.04,0.0,0.04
3,Rafik Belghali,Algeria,DEF,rafik belghali,ITA-Serie A,MF,1920,0.09,0.0,0.09
5,Amine Gouiri,Algeria,FWD,amine gouiri,FRA-Ligue 1,"FW,MF",1326,0.54,0.2,0.75

## Weight Table

In [22]:
import json

# Build weight table for matched non-GK players
matched_weights = merged_filtered[[
    "player", "team", "position", "league", "gls_p90", "ast_p90"
]].copy()
matched_weights["weight_source"] = "fbref"

weight_table = matched_weights.copy()

mins_map = merged_filtered.set_index(["player", "team"])["minutes"].to_dict()
weight_table["minutes"] = weight_table.apply(
    lambda r: mins_map.get((r["player"], r["team"]), 0), axis=1
)
weight_table = (
    weight_table
    .sort_values("minutes", ascending=False)
    .drop_duplicates(subset=["player", "team"], keep="first")
    .drop(columns=["minutes"])
    .reset_index(drop=True)
)


print(f"Players in weight table: {len(weight_table)}")
print(weight_table["weight_source"].value_counts())

with open("../data/league_strength.json") as f:
    league_strength = json.load(f)

max_strength = max(league_strength.values())
weight_table["league_strength"] = (
    weight_table["league"].map(league_strength) / max_strength
).fillna(1.0)

weight_table.to_csv("../data/weight_table.csv", index=False)

Players in weight table: 876
weight_source
fbref    876
Name: count, dtype: int64