## Using `soccerdata` to scrape FBref data

In [1]:
import soccerdata as sd
print(sd.FBref.available_leagues())

[05/27/26 22:40:45] INFO     No custom team name replacements found. You can configure these in       ]8;id=15050755;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_config.py\_config.py]8;;\:]8;id=15050756;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_config.py#92\92]8;;\
                             /Users/fungs4/soccerdata/config/teamname_replacements.json.

                    INFO     Custom league dict loaded from                                          ]8;id=15050762;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_config.py\_config.py]8;;\:]8;id=15050763;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_config.py#188\188]8;;\
                             /Users/fungs4/soccerdata/config/league_dict.json.

['ARG-Primera Division', 'AUT-Bundesliga', 'BEL-First Division A', 'BRA-Serie A', 'Big 5 European Leagues Combined', 'CZE-First League', 'ENG-Premier League', 'ENG2-EFL Championship', 'ESP-La Liga', 'FRA-Ligue 1', 'GER-Bundesliga', 'GRE-Super League', 'INT-European Championship', "INT-Women's World Cup", 'INT-World Cup', 'ITA-Serie A', 'JPN-J1 League', 'KOR-K League 1', 'MEX-Liga MX', 'NED-Eredivisie', 'POR-Primeira Liga', 'SAU-Saudi Pro League', 'SCO-Premiership', 'SUI-Super League', 'TUR-Super Lig', 'USA-MLS']

In [2]:
import soccerdata as sd
import pandas as pd

all_leagues = [
    "ENG-Premier League", "ESP-La Liga", "FRA-Ligue 1", "GER-Bundesliga", "ITA-Serie A",
    "NED-Eredivisie", "POR-Primeira Liga", "SAU-Saudi Pro League", "TUR-Super Lig",
    "BEL-First Division A", "SCO-Premiership", "GRE-Super League", "CZE-First League",
    "AUT-Bundesliga", "SUI-Super League", "BRA-Serie A", "ARG-Primera Division",
    "USA-MLS", "MEX-Liga MX", "KOR-K League 1", "JPN-J1 League", "ENG2-EFL Championship",
]

all_stats = []
for league in all_leagues:
    try:
        fbref = sd.FBref(leagues=[league], seasons=2025)
        s = fbref.read_player_season_stats(stat_type="standard")
        all_stats.append(s)
        print(f"{league}: {s.shape[0]} players")
    except Exception as e:
        print(f"{league}: ERROR — {e}")

stats = pd.concat(all_stats)
print(f"\nTotal players: {stats.shape[0]}")

# Coverage check
players = pd.read_csv("../data/processed/player_fixtures.csv")
wc_players = players[["player", "team", "position"]].drop_duplicates()

stats_names = set(stats.index.get_level_values("player").str.lower().str.strip())
wc_players["name_lower"] = wc_players["player"].str.lower().str.strip()

matched = wc_players[wc_players["name_lower"].isin(stats_names)]
unmatched = wc_players[~wc_players["name_lower"].isin(stats_names)]

print(f"Matched: {len(matched)} ({len(matched)/len(wc_players)*100:.1f}%)")
print(f"Unmatched: {len(unmatched)} ({len(unmatched)/len(wc_players)*100:.1f}%)")

match_rate_by_team = (
    wc_players.groupby("team")
    .apply(lambda g: g["name_lower"].isin(stats_names).mean())
    .sort_values()
)
print("\nTeams with lowest match rates:")
print(match_rate_by_team.head(20))
print("\nTeams with highest match rates:")
print(match_rate_by_team.tail(10))

                    INFO     Saving cached data to /Users/fungs4/soccerdata/data/FBref               ]8;id=15050770;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=15050771;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py#250\250]8;;\

dlopen /usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework: dlopen(/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework, 0x0105): tried: '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file).

ENG-Premier League: 551 players

[05/27/26 22:40:53] INFO     Saving cached data to /Users/fungs4/soccerdata/data/FBref               ]8;id=15050776;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=15050777;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py#250\250]8;;\

dlopen /usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework: dlopen(/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework, 0x0105): tried: '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file).

ESP-La Liga: 611 players

[05/27/26 22:40:57] INFO     Saving cached data to /Users/fungs4/soccerdata/data/FBref               ]8;id=15050782;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=15050783;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py#250\250]8;;\

dlopen /usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework: dlopen(/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework, 0x0105): tried: '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file).

FRA-Ligue 1: 561 players

[05/27/26 22:41:00] INFO     Saving cached data to /Users/fungs4/soccerdata/data/FBref               ]8;id=15050788;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=15050789;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py#250\250]8;;\

dlopen /usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework: dlopen(/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework, 0x0105): tried: '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file).

GER-Bundesliga: 507 players

[05/27/26 22:41:04] INFO     Saving cached data to /Users/fungs4/soccerdata/data/FBref               ]8;id=15050794;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=15050795;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py#250\250]8;;\

dlopen /usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework: dlopen(/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework, 0x0105): tried: '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file).

ITA-Serie A: 609 players

[05/27/26 22:41:08] INFO     Saving cached data to /Users/fungs4/soccerdata/data/FBref               ]8;id=15050800;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=15050801;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py#250\250]8;;\

dlopen /usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework: dlopen(/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework, 0x0105): tried: '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file).

NED-Eredivisie: 550 players

[05/27/26 22:41:10] INFO     Saving cached data to /Users/fungs4/soccerdata/data/FBref               ]8;id=15050806;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=15050807;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py#250\250]8;;\

dlopen /usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework: dlopen(/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework, 0x0105): tried: '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file).

POR-Primeira Liga: 579 players

[05/27/26 22:41:13] INFO     Saving cached data to /Users/fungs4/soccerdata/data/FBref               ]8;id=15050812;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=15050813;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py#250\250]8;;\

dlopen /usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework: dlopen(/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework, 0x0105): tried: '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file).

SAU-Saudi Pro League: 555 players

[05/27/26 22:41:17] INFO     Saving cached data to /Users/fungs4/soccerdata/data/FBref               ]8;id=15050818;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=15050819;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py#250\250]8;;\

dlopen /usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework: dlopen(/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework, 0x0105): tried: '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file).

TUR-Super Lig: 600 players

[05/27/26 22:41:21] INFO     Saving cached data to /Users/fungs4/soccerdata/data/FBref               ]8;id=15050824;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=15050825;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py#250\250]8;;\

dlopen /usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework: dlopen(/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework, 0x0105): tried: '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file).

BEL-First Division A: ERROR — No objects to concatenate

[05/27/26 22:41:25] INFO     Saving cached data to /Users/fungs4/soccerdata/data/FBref               ]8;id=15050830;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=15050831;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py#250\250]8;;\

dlopen /usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework: dlopen(/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework, 0x0105): tried: '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file).

SCO-Premiership: 389 players

[05/27/26 22:41:30] INFO     Saving cached data to /Users/fungs4/soccerdata/data/FBref               ]8;id=15050836;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=15050837;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py#250\250]8;;\

dlopen /usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework: dlopen(/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework, 0x0105): tried: '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file).

GRE-Super League: 466 players

[05/27/26 22:41:34] INFO     Saving cached data to /Users/fungs4/soccerdata/data/FBref               ]8;id=15050842;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=15050843;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py#250\250]8;;\

dlopen /usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework: dlopen(/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework, 0x0105): tried: '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file).

CZE-First League: 561 players

[05/27/26 22:41:37] INFO     Saving cached data to /Users/fungs4/soccerdata/data/FBref               ]8;id=15050848;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=15050849;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py#250\250]8;;\

dlopen /usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework: dlopen(/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework, 0x0105): tried: '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file).

AUT-Bundesliga: 344 players

[05/27/26 22:41:39] INFO     Saving cached data to /Users/fungs4/soccerdata/data/FBref               ]8;id=15050854;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=15050855;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py#250\250]8;;\

dlopen /usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework: dlopen(/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework, 0x0105): tried: '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file).

SUI-Super League: 387 players

[05/27/26 22:41:43] INFO     Saving cached data to /Users/fungs4/soccerdata/data/FBref               ]8;id=15050860;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=15050861;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py#250\250]8;;\

dlopen /usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework: dlopen(/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework, 0x0105): tried: '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file).

BRA-Serie A: 761 players

[05/27/26 22:41:46] INFO     Saving cached data to /Users/fungs4/soccerdata/data/FBref               ]8;id=15050866;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=15050867;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py#250\250]8;;\

dlopen /usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework: dlopen(/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework, 0x0105): tried: '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file).

ARG-Primera Division: 1069 players

[05/27/26 22:41:50] INFO     Saving cached data to /Users/fungs4/soccerdata/data/FBref               ]8;id=15050872;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=15050873;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py#250\250]8;;\

dlopen /usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework: dlopen(/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework, 0x0105): tried: '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file).

USA-MLS: 882 players

[05/27/26 22:41:55] INFO     Saving cached data to /Users/fungs4/soccerdata/data/FBref               ]8;id=15050878;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=15050879;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py#250\250]8;;\

dlopen /usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework: dlopen(/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework, 0x0105): tried: '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file).

MEX-Liga MX: 611 players

[05/27/26 22:41:59] INFO     Saving cached data to /Users/fungs4/soccerdata/data/FBref               ]8;id=15050884;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=15050885;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py#250\250]8;;\

dlopen /usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework: dlopen(/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework, 0x0105): tried: '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file).

KOR-K League 1: 440 players

[05/27/26 22:42:03] INFO     Saving cached data to /Users/fungs4/soccerdata/data/FBref               ]8;id=15050890;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=15050891;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py#250\250]8;;\

dlopen /usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework: dlopen(/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework, 0x0105): tried: '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file).

JPN-J1 League: 632 players

[05/27/26 22:42:07] INFO     Saving cached data to /Users/fungs4/soccerdata/data/FBref               ]8;id=15050896;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=15050897;file:///opt/miniconda3/envs/world-cup-fantasy/lib/python3.11/site-packages/soccerdata/_common.py#250\250]8;;\

dlopen /usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework: dlopen(/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework, 0x0105): tried: '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file), '/usr/local/bin/../Frameworks/Google Chrome for Testing Framework.framework/Versions/138.0.7204.168/Google Chrome for Testing Framework' (no such file).

ENG2-EFL Championship: 791 players

Total players: 12456
Matched: 790 (56.0%)
Unmatched: 620 (44.0%)

Teams with lowest match rates:
team
Qatar                     0.000000
IR Iran                   0.033333
South Africa              0.062500
Uzbekistan                0.066667
Jordan                    0.066667
Egypt                     0.111111
Iraq                      0.235294
Croatia                   0.269231
Bosnia and Herzegovina    0.269231
Panama                    0.304348
New Zealand               0.307692
Haiti                     0.346154
Saudi Arabia              0.400000
Czechia                   0.413793
Cabo Verde                0.423077
Korea Republic            0.423077
Ecuador                   0.441176
Algeria                   0.444444
Morocco                   0.448276
Tunisia                   0.500000
dtype: float64

Teams with highest match rates:
team
Argentina      0.836364
Scotland       0.846154
Austria        0.884615
Switzerland    0.884615
England        0.923077
USA            0.923077
Portugal       0.925926
Netherlands    1.000000
Germany        1.000000
France         1.000000
dtype: float64

## Data Merging

In [3]:
import unicodedata
from rapidfuzz import process, fuzz

def to_ascii(name):
    return unicodedata.normalize('NFKD', name).encode('ascii', 'ignore').decode().lower().strip()

# --- Flatten FBref MultiIndex columns ---
stats_flat = stats.copy()
stats_flat.columns = [
    f"{b}" if not a or a == b else f"{a}_{b}"
    for a, b in stats_flat.columns
]
stats_reset = stats_flat.reset_index()
stats_reset["name_ascii"] = stats_reset["player"].apply(to_ascii)

# --- WC players ---
wc_players = pd.read_csv("../data/processed/player_fixtures.csv")[
    ["player", "team", "position"]
].drop_duplicates()
wc_players["name_ascii"] = wc_players["player"].apply(to_ascii)

# --- Pass 1: exact ASCII match ---
fbref_ascii_set = set(stats_reset["name_ascii"])
exact_matched = wc_players[wc_players["name_ascii"].isin(fbref_ascii_set)].copy()
unmatched = wc_players[~wc_players["name_ascii"].isin(fbref_ascii_set)].copy()
print(f"Exact matches: {len(exact_matched)} | Unmatched: {len(unmatched)}")

# --- Pass 2: fuzzy match constrained by nationality ---
TEAM_TO_NATION = {
    "Algeria": "ALG", "Argentina": "ARG", "Australia": "AUS",
    "Austria": "AUT", "Belgium": "BEL", "Bosnia and Herzegovina": "BIH",
    "Brazil": "BRA", "Cabo Verde": "CPV", "Canada": "CAN", "Chile": "CHI",
    "Colombia": "COL", "Congo DR": "COD", "Costa Rica": "CRC",
    "Croatia": "CRO", "Curaçao": "CUW", "Côte d'Ivoire": "CIV",
    "Czechia": "CZE", "Ecuador": "ECU", "Egypt": "EGY", "England": "ENG",
    "France": "FRA", "Germany": "GER", "Ghana": "GHA", "Greece": "GRE",
    "Haiti": "HAI", "Honduras": "HON", "Hungary": "HUN", "IR Iran": "IRN",
    "Iraq": "IRQ", "Japan": "JPN", "Jordan": "JOR", "Kenya": "KEN",
    "Korea Republic": "KOR", "Mexico": "MEX", "Morocco": "MAR",
    "Netherlands": "NED", "New Zealand": "NZL", "Nigeria": "NGA",
    "Norway": "NOR", "Panama": "PAN", "Paraguay": "PAR", "Peru": "PER",
    "Poland": "POL", "Portugal": "POR", "Qatar": "QAT", "Romania": "ROU",
    "Saudi Arabia": "KSA", "Scotland": "SCO", "Senegal": "SEN",
    "Serbia": "SRB", "Slovakia": "SVK", "Slovenia": "SVN",
    "South Africa": "RSA", "Spain": "ESP", "Sweden": "SWE",
    "Switzerland": "SUI", "Trinidad and Tobago": "TRI", "Tunisia": "TUN",
    "Türkiye": "TUR", "Ukraine": "UKR", "Uruguay": "URU", "USA": "USA",
    "Uzbekistan": "UZB", "Venezuela": "VEN",
}

THRESHOLD = 85
KNOWN_FALSE_POSITIVES = {("Weverton", "Brazil")}

fbref_by_nation = stats_reset[["player", "name_ascii", "nation_"]].drop_duplicates()

fuzzy_rows = []
for _, row in unmatched.iterrows():
    nation_code = TEAM_TO_NATION.get(row["team"])
    if not nation_code:
        continue
    candidates = fbref_by_nation[fbref_by_nation["nation_"] == nation_code]
    if candidates.empty:
        continue
    result = process.extractOne(
        row["name_ascii"],
        candidates["name_ascii"].tolist(),
        scorer=fuzz.token_sort_ratio,
        score_cutoff=THRESHOLD,
    )
    if result and (row["player"], row["team"]) not in KNOWN_FALSE_POSITIVES:
        matched_ascii, score, _ = result
        fuzzy_rows.append({
            "player": row["player"],
            "team": row["team"],
            "position": row["position"],
            "name_ascii": matched_ascii,  # use FBref's ascii so the downstream merge works
        })

fuzzy_matched = pd.DataFrame(fuzzy_rows) if fuzzy_rows else pd.DataFrame(columns=exact_matched.columns)
print(f"Fuzzy matches: {len(fuzzy_matched)}")

matched_players = pd.concat([exact_matched, fuzzy_matched], ignore_index=True)
print(f"Total matched: {len(matched_players)} out of {len(wc_players)} WC players")

Exact matches: 878 | Unmatched: 532
Fuzzy matches: 48
Total matched: 926 out of 1410 WC players

In [4]:
matched_players.head(10)

             player     team position        name_ascii
0   Rayan Aït-Nouri  Algeria      DEF   rayan ait-nouri
1   Ramy Bensebaini  Algeria      DEF   ramy bensebaini
2       Aïssa Mandi  Algeria      DEF       aissa mandi
3    Rafik Belghali  Algeria      DEF    rafik belghali
4      Amine Gouiri  Algeria      FWD      amine gouiri
5      Riyad Mahrez  Algeria      MID      riyad mahrez
6      Ibrahim Maza  Algeria      FWD      ibrahim maza
7  Anis Hadj Moussa  Algeria      FWD  anis hadj moussa
8    Ramiz Zerrouki  Algeria      MID    ramiz zerrouki
9   Hicham Boudaoui  Algeria      MID   hicham boudaoui

Now, we just want to explore the 484 unmatched players

In [5]:
unmatched_final = wc_players[
    ~wc_players["player"].isin(matched_players["player"])
][["player", "team", "position"]].sort_values(["team", "position"]).reset_index(drop=True)

print(f"Unmatched players: {len(unmatched_final)}")
print(unmatched_final.to_string())

Unmatched players: 484
                          player                    team position
0                   Mehdi Dorval                 Algeria      DEF
1               Zinéddine Belaïd                 Algeria      DEF
2                    Sohaib Nair                 Algeria      DEF
3                   Achref Abada                 Algeria      DEF
4                Farès Ghedjemis                 Algeria      FWD
5                Ahmed Benbouali                 Algeria      FWD
6                   Amin Chiakha                 Algeria      FWD
7                Anthony Mandréa                 Algeria       GK
8                    Luca Zidane                 Algeria       GK
9                  Melvin Mastil                 Algeria       GK
10              Kilian Belazzoug                 Algeria       GK
11                 Adil Boulbina                 Algeria      MID
12               Yacine Titraoui                 Algeria      MID
13            Kevin Mac Allister               Argentina      DEF
14              Santiago Beltrán               Argentina       GK
15                      Nico Paz               Argentina      MID
16              Emiliano Buendía               Argentina      MID
17                  Tomás Aranda               Argentina      MID
18                    Jordan Bos               Australia      DEF
19                 Milos Degenek               Australia      DEF
20                   Aziz Behich               Australia      DEF
21                  Fran Karacic               Australia      DEF
22                    Kai Trewin               Australia      DEF
23              Lucas Herrington               Australia      DEF
24             Nishan Velupillay               Australia      FWD
25                    Deni Juric               Australia      FWD
26                     Paul Izzo               Australia       GK
27                 Patrick Beach               Australia       GK
28                     Paul Okon               Australia      MID
29                Alex Robertson               Australia      MID
30                    Awer Mabil               Australia      MID
31               Michael Svoboda                 Austria      DEF
32              Marko Arnautovic                 Austria      FWD
33                 Patrick Pentz                 Austria       GK
34               Brandon Mechele                 Belgium      DEF
35                  Joaquin Seys                 Belgium      DEF
36                  Hans Vanaken                 Belgium      MID
37                  Nikola Katic  Bosnia and Herzegovina      DEF
38              Stjepan Radeljic  Bosnia and Herzegovina      DEF
39           Dennis Hadzikadunic  Bosnia and Herzegovina      DEF
40                    Jovo Lukic  Bosnia and Herzegovina      FWD
41                  Samed Bazdar  Bosnia and Herzegovina      FWD
42                Osman Hadzikic  Bosnia and Herzegovina       GK
43              Martin Zlomislic  Bosnia and Herzegovina       GK
44                 Dzenis Burnic  Bosnia and Herzegovina      MID
45                   Ivan Sunjic  Bosnia and Herzegovina      MID
46                    Ivan Basic  Bosnia and Herzegovina      MID
47            Benjamin Tahirovic  Bosnia and Herzegovina      MID
48                        Ibañez                  Brazil      DEF
49                Douglas Santos                  Brazil      DEF
50                        Bremer                  Brazil      DEF
51                Alisson Becker                  Brazil       GK
52                          Pico              Cabo Verde      DEF
53                  Kelvin Pires              Cabo Verde      DEF
54                         Diney              Cabo Verde      DEF
55                       Stopira              Cabo Verde      DEF
56               Garry Rodrigues              Cabo Verde      FWD
57                  Willy Semedo              Cabo Verde      FWD
58                       Vozinha              Cabo Verde       GK
59                 CJ dos Santos              Cabo Verde       GK
60                Márcio da Rosa              Cabo Verde       GK
61                Yannick Semedo              Cabo Verde      MID
62                    Kevin Pina              Cabo Verde      MID
63                  Deroy Duarte              Cabo Verde      MID
64                  Laros Duarte              Cabo Verde      MID
65                  Hélio Varela              Cabo Verde      MID
66              Gilson Benchimol              Cabo Verde      MID
67            Luc De Fougerolles                  Canada      DEF
68            Jamie Knight-Lebel                  Canada      DEF
69                 Promise David                  Canada      FWD
70                  Owen Goodman                  Canada       GK
71                   Ralph Priso                  Canada      MID
72                    Niko Sigur                  Canada      MID
73               Cucho Hernández                Colombia      FWD
74                  David Ospina                Colombia       GK
75                Álvaro Montero                Colombia       GK
76                Gustavo Puerta                Colombia      MID
77        Juan Fernando Quintero                Colombia      MID
78                 Juan Portilla                Colombia      MID
79                 Joris Kayembe                Congo DR      DEF
80                 Steve Kapuadi                Congo DR      DEF
81                 Gédéon Kalulu                Congo DR      DEF
82                   Simon Banza                Congo DR      FWD
83                 Fiston Mayele                Congo DR      FWD
84               Nathanaël Mbuku                Congo DR      FWD
85                 Brian Cipenga                Congo DR      FWD
86                Matthieu Epolo                Congo DR       GK
87                Timothy Fayulu                Congo DR       GK
88                 Théo Bongonda                Congo DR      MID
89                  Martin Erlic                 Croatia      DEF
90              Dominik Kotarski                 Croatia       GK
91                     Toni Fruk                 Croatia      MID
92                Leandro Bacuna                 Curaçao      DEF
93              Roshon van Eijma                 Curaçao      DEF
94                Ar'Jany Martha                 Curaçao      DEF
95                  Juriën Gaari                 Curaçao      DEF
96                   Kenji Gorré                 Curaçao      FWD
97              Jearl Margaritha                 Curaçao      FWD
98             Gervane Kastaneer                 Curaçao      FWD
99                Jürgen Locadia                 Curaçao      FWD
100                    Eloy Room                 Curaçao       GK
101            Trevor Doornbusch                 Curaçao       GK
102                 Tyrick Bodak                 Curaçao       GK
103          Godfried Roemeratoe                 Curaçao      MID
104                 Kevin Felida                 Curaçao      MID
105                  Evan Ndicka           Côte d'Ivoire      DEF
106                Oumar Diakité           Côte d'Ivoire      FWD
107                 Mohamed Koné           Côte d'Ivoire       GK
108              Parfait Guiagon           Côte d'Ivoire      MID
109            Jean Michaël Seri           Côte d'Ivoire      MID
110                 Joel Ordóñez                 Ecuador      DEF
111                 Félix Torres                 Ecuador      DEF
112                Yaimar Medina                 Ecuador      DEF
113              Deinner Ordóñez                 Ecuador      DEF
114               Fricio Caicedo                 Ecuador      DEF
115              Kevin Rodríguez                 Ecuador      FWD
116                   Alan Minda                 Ecuador      FWD
117                Jordy Caicedo                 Ecuador      FWD
118                Gonzalo Valle                 Ecuador       GK
119               Cristhian Loor                 Ecuador       GK
120               Denil Castillo                 Ecuador      MID
121                Jordy Alcívar                 Ecuador      MID
122                  John Yeboah                 Ecuador      MID
123             Anthony Valencia                 Ecuador      MID
124             Ederson Castillo                 Ecuador      MID
125                Darwin Guagua                 Ecuador      MID
126               Malcom DaCosta                 Ecuador      MID
127                Bruno Caicedo                 Ecuador      MID
128                 Luis Fragozo                 Ecuador      MID
129           Mohamed Abdelmonem                   Egypt      DEF
130                 Ahmed Fatouh                   Egypt      DEF
131                 Mohamed Hany                   Egypt      DEF
132                   Ramy Rabia                   Egypt      DEF
133           Hossam Abdelmaguid                   Egypt      DEF
134                   Tarek Alaa                   Egypt      DEF
135               Yasser Ibrahim                   Egypt      DEF
136                  Karim Hafez                   Egypt      DEF
137                    Trezeguet                   Egypt      FWD
138               Aqtay Abdallah                   Egypt      FWD
139             Hamza Abdelkarim                   Egypt      FWD
140           Mohamed El Shenawy                   Egypt       GK
141             El Mahdy Soliman                   Egypt       GK
142              Mostafa Shobeir                   Egypt       GK
143                 Mohamed Alaa                   Egypt       GK
144                 Marwan Attia                   Egypt      MID
145                         Zizo                   Egypt      MID
146                  Hamdi Fathy                   Egypt      MID
147                  Emam Ashour                   Egypt      MID
148                Mahmoud Saber                   Egypt      MID
149              Mohanad Lasheen                   Egypt      MID
150                 Ibrahim Adel                   Egypt      MID
151             Nabil Emad Dunga                   Egypt      MID
152                 Mostafa Zico                   Egypt      MID
153                   Abdul Baba                   Ghana      DEF
154                   Prince Adu                   Ghana      FWD
155                 Abdul Fatawu                   Ghana      FWD
156       Christopher Bonsu Baah                   Ghana      FWD
157               Benjamin Asare                   Ghana       GK
158                Paul Reverson                   Ghana       GK
159               Solomon Agbasi                   Ghana       GK
160            Lawrence Ati Zigi                   Ghana       GK
161                 Joseph Anang                   Ghana       GK
162             Augustine Boakye                   Ghana      MID
163               Caleb Yirenkyi                   Ghana      MID
164           Jean-Kévin Duverne                   Haiti      DEF
165                  Ricardo Adé                   Haiti      DEF
166            Martin Expérience                   Haiti      DEF
167             Wilguens Paugain                   Haiti      DEF
168                 Duke Lacroix                   Haiti      DEF
169              Keeto Thermoncy                   Haiti      DEF
170                Duckens Nazon                   Haiti      FWD
171               Yassin Fortuné                   Haiti      FWD
172             Ruben Providence                   Haiti      FWD
173                 Lenny Joseph                   Haiti      FWD
174                Johny Placide                   Haiti       GK
175             Alexandre Pierre                   Haiti       GK
176               Josué Duverger                   Haiti       GK
177             Woodensky Pierre                   Haiti      MID
178              Leverton Pierre                   Haiti      MID
179                  Carl Sainté                   Haiti      MID
180          Danley Jean Jacques                   Haiti      MID
181               Ramin Rezaeian                 IR Iran      DEF
182               Hossein Kanani                 IR Iran      DEF
183              Milad Mohammadi                 IR Iran      DEF
184            Shoja Khalilzadeh                 IR Iran      DEF
185               Ehsan Hajisafi                 IR Iran      DEF
186                Saleh Hardani                 IR Iran      DEF
187                   Ali Nemati                 IR Iran      DEF
188                 Aria Yousefi                 IR Iran      DEF
189                  Danial Eiri                 IR Iran      DEF
190          Alireza Jahanbakhsh                 IR Iran      FWD
191                Saman Ghoddos                 IR Iran      FWD
192                  Ali Alipour                 IR Iran      FWD
193               Dennis Dargahi                 IR Iran      FWD
194     Amirhossein Hosseinzadeh                 IR Iran      FWD
195         Amirhossein Mahmoudi                 IR Iran      FWD
196                 Kasra Taheri                 IR Iran      FWD
197           Alireza Beiranvand                 IR Iran       GK
198               Payam Niazmand                 IR Iran       GK
199             Hossein Hosseini                 IR Iran       GK
200            Mohammad Khalifeh                 IR Iran       GK
201    Amir Mohammad Razzaghinia                 IR Iran      MID
202             Hadi Habibinejad                 IR Iran      MID
203            Mohammad Ghorbani                 IR Iran      MID
204               Omid Noorafkan                 IR Iran      MID
205                 Mehdi Torabi                 IR Iran      MID
206              Saeid Ezatolahi                 IR Iran      MID
207              Mohammad Mohebi                 IR Iran      MID
208                Mehdi Ghayedi                 IR Iran      MID
209              Roozbeh Cheshmi                 IR Iran      MID
210                 Frans Putros                    Iraq      DEF
211                 Rebin Sulaka                    Iraq      DEF
212               Maytham Jabbar                    Iraq      DEF
213                  Hussein Ali                    Iraq      DEF
214                 Zaid Tahseen                    Iraq      DEF
215                 Munaf Younus                    Iraq      DEF
216                  Akam Hashim                    Iraq      DEF
217                 Ahmed Maknzi                    Iraq      DEF
218              Mustafa Saadoon                    Iraq      DEF
219                  Ahmed Yahya                    Iraq      DEF
220                Aymen Hussein                    Iraq      FWD
221                  Mohanad Ali                    Iraq      FWD
222                 Youssef Amyn                    Iraq      FWD
223                   Ali Yousif                    Iraq      FWD
224                  Ahmed Basil                    Iraq       GK
225                  Fahad Talib                    Iraq       GK
226                  Kumel Saadi                    Iraq       GK
227                 Jalal Hassan                    Iraq       GK
228                  Zaid Ismael                    Iraq      MID
229                  Marko Farji                    Iraq      MID
230            Hasan Abdulkareem                    Iraq      MID
231                Peter Gwargis                    Iraq      MID
232                  Kevin Yakob                    Iraq      MID
233               Amir Al Ammari                    Iraq      MID
234                   Aimar Sher                    Iraq      MID
235                 Karar Nabeel                    Iraq      MID
236              Shogo Taniguchi                   Japan      DEF
237                 Keisuke Goto                   Japan      FWD
238                    Junya Ito                   Japan      MID
239               Keito Nakamura                   Japan      MID
240               Abdallah Nasib                  Jordan      DEF
241            Mohannad Abu Taha                  Jordan      DEF
242        Mohammad Abu Hasheesh                  Jordan      DEF
243           Husam Abu Al Dahab                  Jordan      DEF
244                Mohammad Taha                  Jordan      DEF
245                  Ahmad Assaf                  Jordan      DEF
246                 Saleem Obaid                  Jordan      DEF
247         Mohammad Abu Al Nadi                  Jordan      DEF
248                  Amer Jamous                  Jordan      DEF
249                 Ehsan Haddad                  Jordan      DEF
250                Saed Al Rosan                  Jordan      DEF
251                  Anas Badawi                  Jordan      DEF
252              Mousa Al Tamari                  Jordan      FWD
253           Mohammad Abu Zraiq                  Jordan      FWD
254             Mahmoud Al Mardi                  Jordan      FWD
255                Odeh Fakhoury                  Jordan      FWD
256                    Ali Olwan                  Jordan      FWD
257             Yazeed  Abulaila                  Jordan       GK
258         Abdallah Al Fakhouri                  Jordan       GK
259             Nour Bani Ateyah                  Jordan       GK
260              Ahmad Al Juaidi                  Jordan       GK
261                 Yousef Qashi                  Jordan      MID
262                Ibrahim Sadeh                  Jordan      MID
263            Mohammad Al Daoud                  Jordan      MID
264             Noor Al Rawabdeh                  Jordan      MID
265             Nizar Al Rashdan                  Jordan      MID
266                 Raja'ei Ayed                  Jordan      MID
267               Seol Young-Woo          Korea Republic      DEF
268                   Cho Yu-Min          Korea Republic      DEF
269                 Lee Han-Beom          Korea Republic      DEF
270                 Cho Gue-Sung          Korea Republic      FWD
271                 César Montes                  Mexico      DEF
272                Jorge Sánchez                  Mexico      DEF
273               Everardo López                  Mexico      DEF
274              Guillermo Ochoa                  Mexico       GK
275                  Raúl Rangel                  Mexico       GK
276                 César Huerta                  Mexico      MID
277                  Luis Chávez                  Mexico      MID
278                 Ismaël Baouf                 Morocco      DEF
279            Youssef Belammari                 Morocco      DEF
280            Soufiane Bouftini                 Morocco      DEF
281                Mohamed Chibi                 Morocco      DEF
282  Ayoube Amaimouni-Echghouyab                 Morocco      FWD
283            Soufiane Benjdida                 Morocco      FWD
284              Tawfik Bentayeb                 Morocco      FWD
285                   Amine Sbaï                 Morocco      FWD
286           El Mehdi Al Harrar                 Morocco       GK
287              Munir El Kajoui                 Morocco       GK
288                Ibrahim Gomis                 Morocco       GK
289             Yanis Benchaouch                 Morocco       GK
290           Soufiane El-Faouzi                 Morocco      MID
291             Francis de Vries             New Zealand      DEF
292                    Tim Payne             New Zealand      DEF
293                Callan Elliot             New Zealand      DEF
294               Nando Pijnaker             New Zealand      DEF
295                  Tommy Smith             New Zealand      DEF
296            Kosta Barbarouses             New Zealand      FWD
297                    Ben Waine             New Zealand      FWD
298                      Ben Old             New Zealand      FWD
299                Jesse Randall             New Zealand      FWD
300              Matthew Garbett             New Zealand      FWD

Manual Mapping

In [6]:
# Pass 3: manual overrides
import sys, os
sys.path.insert(0, os.path.abspath(".."))
from data.manual_overrides import MANUAL_OVERRIDES


still_unmatched = wc_players[~wc_players["player"].isin(matched_players["player"])].copy()

override_rows = []
for _, row in still_unmatched.iterrows():
    fbref_name = MANUAL_OVERRIDES.get(row["player"])
    if fbref_name:
        fbref_ascii = to_ascii(fbref_name)
        override_rows.append({
            "player": row["player"],
            "team": row["team"],
            "position": row["position"],
            "name_ascii": fbref_ascii,
        })

override_matched = pd.DataFrame(override_rows) if override_rows else pd.DataFrame(columns=matched_players.columns)
print(f"Manual override matches: {len(override_matched)}")

matched_players = pd.concat([matched_players, override_matched], ignore_index=True)
print(f"Total matched: {len(matched_players)} / {len(wc_players)} WC players")

Manual override matches: 33
Total matched: 959 / 1410 WC players

In [7]:
unmatched_final = wc_players[
    ~wc_players["player"].isin(matched_players["player"])
][["player", "team", "position"]].sort_values(["team", "position"]).reset_index(drop=True)

print(f"Unmatched players: {len(unmatched_final)}")
print(unmatched_final.to_string())

Unmatched players: 451
                        player                    team position
0                 Mehdi Dorval                 Algeria      DEF
1             Zinéddine Belaïd                 Algeria      DEF
2                  Sohaib Nair                 Algeria      DEF
3                 Achref Abada                 Algeria      DEF
4              Farès Ghedjemis                 Algeria      FWD
5              Ahmed Benbouali                 Algeria      FWD
6                 Amin Chiakha                 Algeria      FWD
7              Anthony Mandréa                 Algeria       GK
8                  Luca Zidane                 Algeria       GK
9                Melvin Mastil                 Algeria       GK
10            Kilian Belazzoug                 Algeria       GK
11               Adil Boulbina                 Algeria      MID
12             Yacine Titraoui                 Algeria      MID
13          Kevin Mac Allister               Argentina      DEF
14            Santiago Beltrán               Argentina       GK
15                Tomás Aranda               Argentina      MID
16               Milos Degenek               Australia      DEF
17                 Aziz Behich               Australia      DEF
18                Fran Karacic               Australia      DEF
19                  Kai Trewin               Australia      DEF
20            Lucas Herrington               Australia      DEF
21           Nishan Velupillay               Australia      FWD
22                  Deni Juric               Australia      FWD
23                   Paul Izzo               Australia       GK
24               Patrick Beach               Australia       GK
25                   Paul Okon               Australia      MID
26              Alex Robertson               Australia      MID
27                  Awer Mabil               Australia      MID
28             Michael Svoboda                 Austria      DEF
29            Marko Arnautovic                 Austria      FWD
30               Patrick Pentz                 Austria       GK
31             Brandon Mechele                 Belgium      DEF
32                Joaquin Seys                 Belgium      DEF
33                Hans Vanaken                 Belgium      MID
34                Nikola Katic  Bosnia and Herzegovina      DEF
35            Stjepan Radeljic  Bosnia and Herzegovina      DEF
36         Dennis Hadzikadunic  Bosnia and Herzegovina      DEF
37                  Jovo Lukic  Bosnia and Herzegovina      FWD
38                Samed Bazdar  Bosnia and Herzegovina      FWD
39              Osman Hadzikic  Bosnia and Herzegovina       GK
40            Martin Zlomislic  Bosnia and Herzegovina       GK
41               Dzenis Burnic  Bosnia and Herzegovina      MID
42                 Ivan Sunjic  Bosnia and Herzegovina      MID
43                  Ivan Basic  Bosnia and Herzegovina      MID
44          Benjamin Tahirovic  Bosnia and Herzegovina      MID
45              Douglas Santos                  Brazil      DEF
46                        Pico              Cabo Verde      DEF
47                Kelvin Pires              Cabo Verde      DEF
48                       Diney              Cabo Verde      DEF
49                     Stopira              Cabo Verde      DEF
50             Garry Rodrigues              Cabo Verde      FWD
51                Willy Semedo              Cabo Verde      FWD
52                     Vozinha              Cabo Verde       GK
53               CJ dos Santos              Cabo Verde       GK
54              Márcio da Rosa              Cabo Verde       GK
55              Yannick Semedo              Cabo Verde      MID
56                  Kevin Pina              Cabo Verde      MID
57                Deroy Duarte              Cabo Verde      MID
58                Laros Duarte              Cabo Verde      MID
59                Hélio Varela              Cabo Verde      MID
60            Gilson Benchimol              Cabo Verde      MID
61          Luc De Fougerolles                  Canada      DEF
62          Jamie Knight-Lebel                  Canada      DEF
63               Promise David                  Canada      FWD
64                Owen Goodman                  Canada       GK
65                  Niko Sigur                  Canada      MID
66                David Ospina                Colombia       GK
67              Álvaro Montero                Colombia       GK
68              Gustavo Puerta                Colombia      MID
69      Juan Fernando Quintero                Colombia      MID
70               Juan Portilla                Colombia      MID
71               Joris Kayembe                Congo DR      DEF
72               Steve Kapuadi                Congo DR      DEF
73               Gédéon Kalulu                Congo DR      DEF
74                 Simon Banza                Congo DR      FWD
75               Fiston Mayele                Congo DR      FWD
76             Nathanaël Mbuku                Congo DR      FWD
77               Brian Cipenga                Congo DR      FWD
78              Matthieu Epolo                Congo DR       GK
79              Timothy Fayulu                Congo DR       GK
80               Théo Bongonda                Congo DR      MID
81                Martin Erlic                 Croatia      DEF
82            Dominik Kotarski                 Croatia       GK
83                   Toni Fruk                 Croatia      MID
84              Leandro Bacuna                 Curaçao      DEF
85            Roshon van Eijma                 Curaçao      DEF
86              Ar'Jany Martha                 Curaçao      DEF
87                Juriën Gaari                 Curaçao      DEF
88                 Kenji Gorré                 Curaçao      FWD
89            Jearl Margaritha                 Curaçao      FWD
90           Gervane Kastaneer                 Curaçao      FWD
91              Jürgen Locadia                 Curaçao      FWD
92                   Eloy Room                 Curaçao       GK
93           Trevor Doornbusch                 Curaçao       GK
94                Tyrick Bodak                 Curaçao       GK
95         Godfried Roemeratoe                 Curaçao      MID
96                Kevin Felida                 Curaçao      MID
97               Oumar Diakité           Côte d'Ivoire      FWD
98                Mohamed Koné           Côte d'Ivoire       GK
99             Parfait Guiagon           Côte d'Ivoire      MID
100          Jean Michaël Seri           Côte d'Ivoire      MID
101               Joel Ordóñez                 Ecuador      DEF
102               Félix Torres                 Ecuador      DEF
103              Yaimar Medina                 Ecuador      DEF
104            Deinner Ordóñez                 Ecuador      DEF
105             Fricio Caicedo                 Ecuador      DEF
106            Kevin Rodríguez                 Ecuador      FWD
107                 Alan Minda                 Ecuador      FWD
108              Jordy Caicedo                 Ecuador      FWD
109              Gonzalo Valle                 Ecuador       GK
110             Cristhian Loor                 Ecuador       GK
111             Denil Castillo                 Ecuador      MID
112              Jordy Alcívar                 Ecuador      MID
113                John Yeboah                 Ecuador      MID
114           Anthony Valencia                 Ecuador      MID
115           Ederson Castillo                 Ecuador      MID
116              Darwin Guagua                 Ecuador      MID
117             Malcom DaCosta                 Ecuador      MID
118              Bruno Caicedo                 Ecuador      MID
119               Luis Fragozo                 Ecuador      MID
120         Mohamed Abdelmonem                   Egypt      DEF
121               Ahmed Fatouh                   Egypt      DEF
122               Mohamed Hany                   Egypt      DEF
123                 Ramy Rabia                   Egypt      DEF
124         Hossam Abdelmaguid                   Egypt      DEF
125                 Tarek Alaa                   Egypt      DEF
126             Yasser Ibrahim                   Egypt      DEF
127                Karim Hafez                   Egypt      DEF
128                  Trezeguet                   Egypt      FWD
129             Aqtay Abdallah                   Egypt      FWD
130           Hamza Abdelkarim                   Egypt      FWD
131         Mohamed El Shenawy                   Egypt       GK
132           El Mahdy Soliman                   Egypt       GK
133            Mostafa Shobeir                   Egypt       GK
134               Mohamed Alaa                   Egypt       GK
135               Marwan Attia                   Egypt      MID
136                       Zizo                   Egypt      MID
137                Hamdi Fathy                   Egypt      MID
138                Emam Ashour                   Egypt      MID
139              Mahmoud Saber                   Egypt      MID
140            Mohanad Lasheen                   Egypt      MID
141               Ibrahim Adel                   Egypt      MID
142               Mostafa Zico                   Egypt      MID
143                 Abdul Baba                   Ghana      DEF
144               Abdul Fatawu                   Ghana      FWD
145             Benjamin Asare                   Ghana       GK
146              Paul Reverson                   Ghana       GK
147             Solomon Agbasi                   Ghana       GK
148               Joseph Anang                   Ghana       GK
149           Augustine Boakye                   Ghana      MID
150             Caleb Yirenkyi                   Ghana      MID
151         Jean-Kévin Duverne                   Haiti      DEF
152                Ricardo Adé                   Haiti      DEF
153          Martin Expérience                   Haiti      DEF
154           Wilguens Paugain                   Haiti      DEF
155               Duke Lacroix                   Haiti      DEF
156            Keeto Thermoncy                   Haiti      DEF
157              Duckens Nazon                   Haiti      FWD
158             Yassin Fortuné                   Haiti      FWD
159           Ruben Providence                   Haiti      FWD
160               Lenny Joseph                   Haiti      FWD
161              Johny Placide                   Haiti       GK
162           Alexandre Pierre                   Haiti       GK
163             Josué Duverger                   Haiti       GK
164           Woodensky Pierre                   Haiti      MID
165            Leverton Pierre                   Haiti      MID
166                Carl Sainté                   Haiti      MID
167             Ramin Rezaeian                 IR Iran      DEF
168             Hossein Kanani                 IR Iran      DEF
169            Milad Mohammadi                 IR Iran      DEF
170          Shoja Khalilzadeh                 IR Iran      DEF
171             Ehsan Hajisafi                 IR Iran      DEF
172              Saleh Hardani                 IR Iran      DEF
173                 Ali Nemati                 IR Iran      DEF
174               Aria Yousefi                 IR Iran      DEF
175                Danial Eiri                 IR Iran      DEF
176        Alireza Jahanbakhsh                 IR Iran      FWD
177              Saman Ghoddos                 IR Iran      FWD
178                Ali Alipour                 IR Iran      FWD
179             Dennis Dargahi                 IR Iran      FWD
180   Amirhossein Hosseinzadeh                 IR Iran      FWD
181       Amirhossein Mahmoudi                 IR Iran      FWD
182               Kasra Taheri                 IR Iran      FWD
183         Alireza Beiranvand                 IR Iran       GK
184             Payam Niazmand                 IR Iran       GK
185           Hossein Hosseini                 IR Iran       GK
186          Mohammad Khalifeh                 IR Iran       GK
187  Amir Mohammad Razzaghinia                 IR Iran      MID
188           Hadi Habibinejad                 IR Iran      MID
189          Mohammad Ghorbani                 IR Iran      MID
190             Omid Noorafkan                 IR Iran      MID
191               Mehdi Torabi                 IR Iran      MID
192            Saeid Ezatolahi                 IR Iran      MID
193            Mohammad Mohebi                 IR Iran      MID
194              Mehdi Ghayedi                 IR Iran      MID
195            Roozbeh Cheshmi                 IR Iran      MID
196               Frans Putros                    Iraq      DEF
197               Rebin Sulaka                    Iraq      DEF
198             Maytham Jabbar                    Iraq      DEF
199                Hussein Ali                    Iraq      DEF
200               Zaid Tahseen                    Iraq      DEF
201               Munaf Younus                    Iraq      DEF
202                Akam Hashim                    Iraq      DEF
203               Ahmed Maknzi                    Iraq      DEF
204            Mustafa Saadoon                    Iraq      DEF
205                Ahmed Yahya                    Iraq      DEF
206              Aymen Hussein                    Iraq      FWD
207                Mohanad Ali                    Iraq      FWD
208               Youssef Amyn                    Iraq      FWD
209                 Ali Yousif                    Iraq      FWD
210                Ahmed Basil                    Iraq       GK
211                Fahad Talib                    Iraq       GK
212                Kumel Saadi                    Iraq       GK
213               Jalal Hassan                    Iraq       GK
214                Zaid Ismael                    Iraq      MID
215                Marko Farji                    Iraq      MID
216          Hasan Abdulkareem                    Iraq      MID
217              Peter Gwargis                    Iraq      MID
218                Kevin Yakob                    Iraq      MID
219             Amir Al Ammari                    Iraq      MID
220                 Aimar Sher                    Iraq      MID
221               Karar Nabeel                    Iraq      MID
222            Shogo Taniguchi                   Japan      DEF
223               Keisuke Goto                   Japan      FWD
224                  Junya Ito                   Japan      MID
225             Keito Nakamura                   Japan      MID
226             Abdallah Nasib                  Jordan      DEF
227          Mohannad Abu Taha                  Jordan      DEF
228      Mohammad Abu Hasheesh                  Jordan      DEF
229         Husam Abu Al Dahab                  Jordan      DEF
230              Mohammad Taha                  Jordan      DEF
231                Ahmad Assaf                  Jordan      DEF
232               Saleem Obaid                  Jordan      DEF
233       Mohammad Abu Al Nadi                  Jordan      DEF
234                Amer Jamous                  Jordan      DEF
235               Ehsan Haddad                  Jordan      DEF
236              Saed Al Rosan                  Jordan      DEF
237                Anas Badawi                  Jordan      DEF
238         Mohammad Abu Zraiq                  Jordan      FWD
239           Mahmoud Al Mardi                  Jordan      FWD
240              Odeh Fakhoury                  Jordan      FWD
241                  Ali Olwan                  Jordan      FWD
242           Yazeed  Abulaila                  Jordan       GK
243       Abdallah Al Fakhouri                  Jordan       GK
244           Nour Bani Ateyah                  Jordan       GK
245            Ahmad Al Juaidi                  Jordan       GK
246               Yousef Qashi                  Jordan      MID
247              Ibrahim Sadeh                  Jordan      MID
248          Mohammad Al Daoud                  Jordan      MID
249           Noor Al Rawabdeh                  Jordan      MID
250           Nizar Al Rashdan                  Jordan      MID
251               Raja'ei Ayed                  Jordan      MID
252             Seol Young-Woo          Korea Republic      DEF
253                 Cho Yu-Min          Korea Republic      DEF
254               Lee Han-Beom          Korea Republic      DEF
255               Cho Gue-Sung          Korea Republic      FWD
256               César Montes                  Mexico      DEF
257             Everardo López                  Mexico      DEF
258            Guillermo Ochoa                  Mexico       GK
259                Raúl Rangel                  Mexico       GK
260               César Huerta                  Mexico      MID
261                Luis Chávez                  Mexico      MID
262               Ismaël Baouf                 Morocco      DEF
263          Youssef Belammari                 Morocco      DEF
264          Soufiane Bouftini                 Morocco      DEF
265              Mohamed Chibi                 Morocco      DEF
266          Soufiane Benjdida                 Morocco      FWD
267            Tawfik Bentayeb                 Morocco      FWD
268                 Amine Sbaï                 Morocco      FWD
269         El Mehdi Al Harrar                 Morocco       GK
270            Munir El Kajoui                 Morocco       GK
271              Ibrahim Gomis                 Morocco       GK
272           Yanis Benchaouch                 Morocco       GK
273         Soufiane El-Faouzi                 Morocco      MID
274           Francis de Vries             New Zealand      DEF
275                  Tim Payne             New Zealand      DEF
276              Callan Elliot             New Zealand      DEF
277             Nando Pijnaker             New Zealand      DEF
278                Tommy Smith             New Zealand      DEF
279          Kosta Barbarouses             New Zealand      FWD
280                  Ben Waine             New Zealand      FWD
281                    Ben Old             New Zealand      FWD
282              Jesse Randall             New Zealand      FWD
283            Matthew Garbett             New Zealand      FWD
284               Alex Paulsen             New Zealand       GK
285               Michael Woud             New Zealand       GK
286            Callum McCowatt             New Zealand      MID
287                 Alex Rufer             New Zealand      MID
288                   Joe Bell             New Zealand      MID
289            Lachlan Bayliss             New Zealand      MID
290             Sarpreet Singh             New Zealand      MID
291            Fredrik Bjørkan                  Norway      DEF
292           Henrik Falchener                  Norway      DEF
293               Patrick Berg                  Norway      MID
294          Jens Petter Hauge                  Norway      MID
295                 Éric Davis                  Panama      DEF
296             César Blackman                  Panama      DEF
297            Roderick Miller                  Panama      DEF
298              Jiovany Ramos                  Panama      DEF
299                Martín Krug                  Panama      DEF
300            Jorge Gutiérrez                  Panama      DEF
301               José Fajardo                  Panama      FWD
302           Cecilio Waterman                  Panama      FWD
303                César Yanis                  Panama      FWD
304                 Luis Mejía                  Panama       GK
305              César Samudio                  Panama       GK
306          Cristian Martínez                  Panama      MID
307          Gustavo Velázquez                Paraguay      DEF
308          Juan José Cáceres                Paraguay      DEF
309            Alcides Benítez                Paraguay      DEF
310                 Diego León                Paraguay      DEF

Here, we merge the `matched_players` dataframe with the relevant FBRef data

In [8]:
import numpy as np

# Step 1: Merge with league included
merged = matched_players.merge(
    stats_reset[[
        "name_ascii", "league", "pos_",
        "Playing Time_Min",
        "Per 90 Minutes_Gls", "Per 90 Minutes_Ast", "Per 90 Minutes_G+A"
    ]],
    on="name_ascii",
    how="left"
).rename(columns={
    "pos_": "fbref_pos",
    "Playing Time_Min": "minutes",
    "Per 90 Minutes_Gls": "gls_p90",
    "Per 90 Minutes_Ast": "ast_p90",
    "Per 90 Minutes_G+A": "ga_p90"
})

# Step 2: Apply minimum minutes filter
MIN_MINS = 900
merged_filtered = merged[merged["minutes"] >= MIN_MINS].copy()
print(f"Players after {MIN_MINS} min filter: {len(merged_filtered)}")

# Step 3: League-normalise within position group
# Use the full stats_reset (not just WC players) as the reference population
# so percentiles are relative to all players in that league, not just WC squad players
ref = stats_reset[stats_reset["Playing Time_Min"] >= MIN_MINS].copy().rename(columns={
    "pos_": "fbref_pos",
    "Playing Time_Min": "minutes",
    "Per 90 Minutes_Gls": "gls_p90",
    "Per 90 Minutes_Ast": "ast_p90",
    "Per 90 Minutes_G+A": "ga_p90"
})

for stat in ["gls_p90", "ast_p90", "ga_p90"]:
    ref[f"{stat}_pct"] = ref.groupby(["league", "fbref_pos"])[stat].rank(pct=True)

# Merge percentiles back via a join instead of index mapping
pct_cols = ["name_ascii", "league", "gls_p90_pct", "ast_p90_pct", "ga_p90_pct"]
merged_filtered = merged_filtered.merge(
    ref[pct_cols].drop_duplicates(subset=["name_ascii", "league"]),
    on=["name_ascii", "league"],
    how="left"
)

Players after 900 min filter: 858

In [9]:
merged_filtered.head()

,player,team,position,name_ascii,league,fbref_pos,minutes,gls_p90,ast_p90,ga_p90,gls_p90_pct,ast_p90_pct,ga_p90_pct
0,Rayan Aït-Nouri,Algeria,DEF,rayan ait-nouri,ENG-Premier League,DF,974,0.0,0.18,0.18,0.223958,0.973958,0.885417
1,Ramy Bensebaini,Algeria,DEF,ramy bensebaini,GER-Bundesliga,DF,1530,0.29,0.12,0.41,1.0,0.902985,0.985075
2,Aïssa Mandi,Algeria,DEF,aissa mandi,FRA-Ligue 1,DF,2424,0.04,0.0,0.04,0.664384,0.239726,0.376712
3,Rafik Belghali,Algeria,DEF,rafik belghali,ITA-Serie A,MF,1920,0.09,0.0,0.09,0.546729,0.116822,0.313084
4,Amine Gouiri,Algeria,FWD,amine gouiri,FRA-Ligue 1,"FW,MF",1326,0.54,0.2,0.75,0.923077,0.846154,0.846154

## Weight Table

In [10]:
import json

# Build weight table for matched non-GK players
matched_weights = merged_filtered[[
    "player", "team", "position", "league", "gls_p90_pct", "ast_p90_pct"
]].copy()
matched_weights["weight_source"] = "fbref"

weight_table = matched_weights.copy()

mins_map = merged_filtered.set_index(["player", "team"])["minutes"].to_dict()
weight_table["minutes"] = weight_table.apply(
    lambda r: mins_map.get((r["player"], r["team"]), 0), axis=1
)
weight_table = (
    weight_table
    .sort_values("minutes", ascending=False)
    .drop_duplicates(subset=["player", "team"], keep="first")
    .drop(columns=["minutes"])
    .reset_index(drop=True)
)

# Override all GKs with neutral weights
weight_table.loc[weight_table["position"] == "GK", "gls_p90_pct"] = 0
weight_table.loc[weight_table["position"] == "GK", "ast_p90_pct"] = 0
weight_table.loc[weight_table["position"] == "GK", "weight_source"] = "gk_neutral"

print(f"Players in weight table: {len(weight_table)}")
print(weight_table["weight_source"].value_counts())

with open("../data/league_strength.json") as f:
    league_strength = json.load(f)

max_strength = max(league_strength.values())
weight_table["league_strength"] = (
    weight_table["league"].map(league_strength) / max_strength
).fillna(1.0)

weight_table.to_csv("../data/weight_table.csv", index=False)

Players in weight table: 824
weight_source
fbref         746
gk_neutral     78
Name: count, dtype: int64